name: landing_page_screen
description: A new Flutter package project.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  freezed_annotation: ^2.4.1

  intl: ^0.18.0
  toast: ^0.3.0
  oxidized: ^5.2.0
  flutter_svg: ^1.1.0
  launch_review: ^3.0.1
  package_info_plus: ^4.0.1

  # Internal packages
  component_library:
    path: ../../component_library
  database:
    path: ../../database
  io_library:
    path: ../../io_library
  workspace_screen:
    path: ../workspace_screen

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^5.2.0
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^2.0.1
  floor_generator: ^1.2.0
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2
  build_runner: ^2.2.0
  freezed: ^2.4.1

flutter:
