name: io_library
description: A new Flutter package project.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  freezed_annotation: ^2.4.1
  logging: ^1.0.2
  protobuf: ^2.1.0
  path_provider: ^2.0.11
  file_picker: ^5.3.1
  image: ^3.2.0
  package_info_plus: ^4.0.1
  device_info_plus: ^9.0.3
  permission_handler: ^10.0.0
  image_picker: ^0.8.5+3
  filesize: ^2.0.1
  oxidized: ^5.2.0
  intl: ^0.18.0
  json_annotation: ^4.8.1

  # Internal packages:
  component_library:
    path: ../component_library
  command:
    path: ../command
  database:
    path: ../database
  workspace_screen:
    path: ../features/workspace_screen
  import_sorter: ^4.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^5.2.0
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^2.0.1
  floor_generator: ^1.2.0
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2
  build_runner: ^2.2.0
  freezed: ^2.4.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - test/fixture/image/
