// Mocks generated by Mockito 5.4.5 from annotations
// in paintroid/test/unit/provider/save_as_raster_image_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i11;
import 'dart:typed_data' as _i7;
import 'dart:ui' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:oxidized/oxidized.dart' as _i4;
import 'package:paintroid/core/providers/object/file_service.dart' as _i10;
import 'package:paintroid/core/providers/object/image_service.dart' as _i2;
import 'package:paintroid/core/providers/object/permission_service.dart'
    as _i12;
import 'package:paintroid/core/providers/object/photo_library_service.dart'
    as _i9;
import 'package:paintroid/core/utils/failure.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IImageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIImageService extends _i1.Mock implements _i2.IImageService {
  MockIImageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.Image, _i6.Failure>> import(
          _i7.Uint8List? fileData) =>
      (super.noSuchMethod(
        Invocation.method(
          #import,
          [fileData],
        ),
        returnValue: _i3.Future<_i4.Result<_i5.Image, _i6.Failure>>.value(
            _i8.dummyValue<_i4.Result<_i5.Image, _i6.Failure>>(
          this,
          Invocation.method(
            #import,
            [fileData],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.Image, _i6.Failure>>);

  @override
  _i3.Future<_i4.Result<_i7.Uint8List, _i6.Failure>> exportAsJpg(
    _i5.Image? image,
    int? quality,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportAsJpg,
          [
            image,
            quality,
          ],
        ),
        returnValue: _i3.Future<_i4.Result<_i7.Uint8List, _i6.Failure>>.value(
            _i8.dummyValue<_i4.Result<_i7.Uint8List, _i6.Failure>>(
          this,
          Invocation.method(
            #exportAsJpg,
            [
              image,
              quality,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i7.Uint8List, _i6.Failure>>);

  @override
  _i3.Future<_i4.Result<_i7.Uint8List, _i6.Failure>> exportAsPng(
          _i5.Image? image) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportAsPng,
          [image],
        ),
        returnValue: _i3.Future<_i4.Result<_i7.Uint8List, _i6.Failure>>.value(
            _i8.dummyValue<_i4.Result<_i7.Uint8List, _i6.Failure>>(
          this,
          Invocation.method(
            #exportAsPng,
            [image],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i7.Uint8List, _i6.Failure>>);

  @override
  _i4.Result<_i7.Uint8List, _i6.Failure> getProjectPreview(String? path) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProjectPreview,
          [path],
        ),
        returnValue: _i8.dummyValue<_i4.Result<_i7.Uint8List, _i6.Failure>>(
          this,
          Invocation.method(
            #getProjectPreview,
            [path],
          ),
        ),
      ) as _i4.Result<_i7.Uint8List, _i6.Failure>);
}

/// A class which mocks [IPhotoLibraryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIPhotoLibraryService extends _i1.Mock
    implements _i9.IPhotoLibraryService {
  MockIPhotoLibraryService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i4.Unit, _i6.Failure>> save(
    String? filename,
    _i7.Uint8List? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #save,
          [
            filename,
            data,
          ],
        ),
        returnValue: _i3.Future<_i4.Result<_i4.Unit, _i6.Failure>>.value(
            _i8.dummyValue<_i4.Result<_i4.Unit, _i6.Failure>>(
          this,
          Invocation.method(
            #save,
            [
              filename,
              data,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i4.Unit, _i6.Failure>>);

  @override
  _i3.Future<_i4.Result<_i7.Uint8List, _i6.Failure>> pick() =>
      (super.noSuchMethod(
        Invocation.method(
          #pick,
          [],
        ),
        returnValue: _i3.Future<_i4.Result<_i7.Uint8List, _i6.Failure>>.value(
            _i8.dummyValue<_i4.Result<_i7.Uint8List, _i6.Failure>>(
          this,
          Invocation.method(
            #pick,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i7.Uint8List, _i6.Failure>>);
}

/// A class which mocks [IFileService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIFileService extends _i1.Mock implements _i10.IFileService {
  MockIFileService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i11.File, _i6.Failure>> save(
    String? filename,
    _i7.Uint8List? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #save,
          [
            filename,
            data,
          ],
        ),
        returnValue: _i3.Future<_i4.Result<_i11.File, _i6.Failure>>.value(
            _i8.dummyValue<_i4.Result<_i11.File, _i6.Failure>>(
          this,
          Invocation.method(
            #save,
            [
              filename,
              data,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i11.File, _i6.Failure>>);

  @override
  _i3.Future<_i4.Result<_i11.File, _i6.Failure>> saveToApplicationDirectory(
    String? filename,
    _i7.Uint8List? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveToApplicationDirectory,
          [
            filename,
            data,
          ],
        ),
        returnValue: _i3.Future<_i4.Result<_i11.File, _i6.Failure>>.value(
            _i8.dummyValue<_i4.Result<_i11.File, _i6.Failure>>(
          this,
          Invocation.method(
            #saveToApplicationDirectory,
            [
              filename,
              data,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i11.File, _i6.Failure>>);

  @override
  _i3.Future<_i4.Result<_i11.File, _i6.Failure>> pick() => (super.noSuchMethod(
        Invocation.method(
          #pick,
          [],
        ),
        returnValue: _i3.Future<_i4.Result<_i11.File, _i6.Failure>>.value(
            _i8.dummyValue<_i4.Result<_i11.File, _i6.Failure>>(
          this,
          Invocation.method(
            #pick,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i11.File, _i6.Failure>>);

  @override
  _i4.Result<_i11.File, _i6.Failure> getFile(String? path) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFile,
          [path],
        ),
        returnValue: _i8.dummyValue<_i4.Result<_i11.File, _i6.Failure>>(
          this,
          Invocation.method(
            #getFile,
            [path],
          ),
        ),
      ) as _i4.Result<_i11.File, _i6.Failure>);

  @override
  _i3.Future<bool> checkIfFileExistsInApplicationDirectory(String? fileName) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkIfFileExistsInApplicationDirectory,
          [fileName],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<_i4.Result<_i11.FileSystemEntity, _i6.Failure>>
      deleteFileInApplicationDirectory(String? fileName) => (super.noSuchMethod(
            Invocation.method(
              #deleteFileInApplicationDirectory,
              [fileName],
            ),
            returnValue: _i3
                .Future<_i4.Result<_i11.FileSystemEntity, _i6.Failure>>.value(
                _i8.dummyValue<_i4.Result<_i11.FileSystemEntity, _i6.Failure>>(
              this,
              Invocation.method(
                #deleteFileInApplicationDirectory,
                [fileName],
              ),
            )),
          ) as _i3.Future<_i4.Result<_i11.FileSystemEntity, _i6.Failure>>);
}

/// A class which mocks [IPermissionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIPermissionService extends _i1.Mock
    implements _i12.IPermissionService {
  MockIPermissionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> requestAccessToPickPhotos() => (super.noSuchMethod(
        Invocation.method(
          #requestAccessToPickPhotos,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> requestAccessForSavingToPhotos() => (super.noSuchMethod(
        Invocation.method(
          #requestAccessForSavingToPhotos,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> requestAccessToSharedFileStorage() => (super.noSuchMethod(
        Invocation.method(
          #requestAccessToSharedFileStorage,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
