include: package:flutter_lints/flutter.yaml
linter:
  rules:
    always_use_package_imports: true
    avoid_relative_lib_imports: true
    prefer_relative_imports: false
    prefer_single_quotes: true
    avoid_void_async: true
    constant_identifier_names: false

analyzer:
  errors:
    missing_enum_constant_in_switch: error
    exhaustive_cases: error
    unused_element: error
    type_annotate_public_apis: error
    missing_required_param: error
    invalid_use_of_protected_member: error
    unused_import: error

  exclude:
    - lib/src/**.pb*.dart
    - lib/**.g.dart