name: paintroid
description: The standard image manipulation app for Catroid.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_localization: ^0.3.2
  intl: ^0.20.2
  logging: ^1.0.2
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  shared_preferences: ^2.0.15
  freezed_annotation: ^2.4.1
  equatable: ^2.0.3
  json_annotation: ^4.8.1
  collection: ^1.17.1
  url_launcher: ^6.1.6
  toast: ^0.3.0
  oxidized: ^5.2.0
  flutter_svg: ^1.1.0
  package_info_plus: ^8.3.0
  filesize: ^2.0.1
  smooth_page_indicator: ^1.0.0+2
  image: ^3.2.0
  permission_handler: ^11.4.0
  device_info_plus: ^9.1.2
  image_picker: ^1.1.2
  path_provider: ^2.0.11
  file_picker: ^8.3.5
  floor: ^1.2.0
  sqflite: ^2.3.0
  path_drawing: ^1.0.1
  colorpicker:
    path: packages/colorpicker

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  mockito: ^5.2.0
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^5.0.0
  floor_generator: ^1.4.2
  riverpod_generator: ^2.2.4
  riverpod_lint: ^2.0.0
  build_runner: ^2.2.0
  freezed: ^2.4.1
  riverpod: ^2.3.7
  json_serializable: ^6.7.1


flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter.ttf
    - family: Cursive
      fonts:
        - asset: assets/fonts/cursive.ttf
    - family: Dancing
      fonts:
        - asset: assets/fonts/dancing.ttf
    - family: Open Sans
      fonts:
        - asset: assets/fonts/open_sans.ttf
    - family: Monospace
      fonts:
        - asset: assets/fonts/mono_space.ttf
    - family: Sans Serif Shaded
      fonts:
        - asset: assets/fonts/sans_serif_shade.ttf
    - family: Wind
      fonts:
        - asset: assets/fonts/wind.ttf
    - family: Space Mono
      fonts:
        - asset: assets/fonts/space_mono.ttf
    - family: Work Sans
      fonts:
        - asset: assets/fonts/work_sans.ttf

  assets:
    - assets/icon/
    - assets/img/
    - assets/svg/
    - assets/lang/
    - test/assets/images/
    - assets/pr_number.txt
