arb-dir: assets/lang
template-arb-file: colorpicker_translations_en.arb

output-dir: lib/src/localization
output-localization-file: colorpicker_localizations.dart
output-class: ColorPickerLocalizations