name: colorpicker
description: "A new Flutter package project."
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

# this package should be built separately and not depend on other app modules
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  riverpod_generator: ^2.2.3
  riverpod_lint: ^2.1.1
  freezed: ^2.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/img/