name: colorpicker
description: "A new Flutter package project."
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

# this package should be built separately and not depend on other app modules
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/