// Mocks generated by Mockito 5.4.4 from annotations
// in paintroid/test/unit/tools/clipboard_tool_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i29;
import 'dart:typed_data' as _i27;
import 'dart:ui' as _i2;

import 'package:flutter/material.dart' as _i28;
import 'package:logging/logging.dart' as _i16;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i20;
import 'package:paintroid/core/commands/command_factory/command_factory.dart'
    as _i24;
import 'package:paintroid/core/commands/command_implementation/command.dart'
    as _i3;
import 'package:paintroid/core/commands/command_implementation/graphic/clipboard_command.dart'
    as _i9;
import 'package:paintroid/core/commands/command_implementation/graphic/color_changed_command.dart'
    as _i15;
import 'package:paintroid/core/commands/command_implementation/graphic/delete_region_command.dart'
    as _i14;
import 'package:paintroid/core/commands/command_implementation/graphic/graphic_command.dart'
    as _i22;
import 'package:paintroid/core/commands/command_implementation/graphic/line_command.dart'
    as _i6;
import 'package:paintroid/core/commands/command_implementation/graphic/path_command.dart'
    as _i5;
import 'package:paintroid/core/commands/command_implementation/graphic/shape/ellipse_shape_command.dart'
    as _i8;
import 'package:paintroid/core/commands/command_implementation/graphic/shape/heart_shape_command.dart'
    as _i12;
import 'package:paintroid/core/commands/command_implementation/graphic/shape/square_shape_command.dart'
    as _i7;
import 'package:paintroid/core/commands/command_implementation/graphic/shape/star_shape_command.dart'
    as _i11;
import 'package:paintroid/core/commands/command_implementation/graphic/spray_command.dart'
    as _i13;
import 'package:paintroid/core/commands/command_implementation/graphic/text_command.dart'
    as _i10;
import 'package:paintroid/core/commands/command_manager/command_manager.dart'
    as _i21;
import 'package:paintroid/core/commands/path_with_action_history.dart' as _i25;
import 'package:paintroid/core/enums/bounding_box_action.dart' as _i18;
import 'package:paintroid/core/enums/bounding_box_resize_action.dart' as _i19;
import 'package:paintroid/core/enums/shape_style.dart' as _i26;
import 'package:paintroid/core/tools/bounding_box.dart' as _i17;
import 'package:paintroid/core/tools/line_tool/vertex_stack.dart' as _i23;
import 'package:paintroid/core/tools/tool_data.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeOffset_0 extends _i1.SmartFake implements _i2.Offset {
  _FakeOffset_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRect_1 extends _i1.SmartFake implements _i2.Rect {
  _FakeRect_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCommand_2 extends _i1.SmartFake implements _i3.Command {
  _FakeCommand_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeToolData_3 extends _i1.SmartFake implements _i4.ToolData {
  _FakeToolData_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePathCommand_4 extends _i1.SmartFake implements _i5.PathCommand {
  _FakePathCommand_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLineCommand_5 extends _i1.SmartFake implements _i6.LineCommand {
  _FakeLineCommand_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSquareShapeCommand_6 extends _i1.SmartFake
    implements _i7.SquareShapeCommand {
  _FakeSquareShapeCommand_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEllipseShapeCommand_7 extends _i1.SmartFake
    implements _i8.EllipseShapeCommand {
  _FakeEllipseShapeCommand_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClipboardCommand_8 extends _i1.SmartFake
    implements _i9.ClipboardCommand {
  _FakeClipboardCommand_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTextCommand_9 extends _i1.SmartFake implements _i10.TextCommand {
  _FakeTextCommand_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStarShapeCommand_10 extends _i1.SmartFake
    implements _i11.StarShapeCommand {
  _FakeStarShapeCommand_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHeartShapeCommand_11 extends _i1.SmartFake
    implements _i12.HeartShapeCommand {
  _FakeHeartShapeCommand_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSprayCommand_12 extends _i1.SmartFake implements _i13.SprayCommand {
  _FakeSprayCommand_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeleteRegionCommand_13 extends _i1.SmartFake
    implements _i14.DeleteRegionCommand {
  _FakeDeleteRegionCommand_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeColorChangedCommand_14 extends _i1.SmartFake
    implements _i15.ColorChangedCommand {
  _FakeColorChangedCommand_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLogger_15 extends _i1.SmartFake implements _i16.Logger {
  _FakeLogger_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeImage_16 extends _i1.SmartFake implements _i2.Image {
  _FakeImage_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BoundingBox].
///
/// See the documentation for Mockito's code generation for more information.
class MockBoundingBox extends _i1.Mock implements _i17.BoundingBox {
  MockBoundingBox() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Offset get center => (super.noSuchMethod(
        Invocation.getter(#center),
        returnValue: _FakeOffset_0(
          this,
          Invocation.getter(#center),
        ),
      ) as _i2.Offset);

  @override
  set center(_i2.Offset? _center) => super.noSuchMethod(
        Invocation.setter(
          #center,
          _center,
        ),
        returnValueForMissingStub: null,
      );

  @override
  double get width => (super.noSuchMethod(
        Invocation.getter(#width),
        returnValue: 0.0,
      ) as double);

  @override
  set width(double? _width) => super.noSuchMethod(
        Invocation.setter(
          #width,
          _width,
        ),
        returnValueForMissingStub: null,
      );

  @override
  double get height => (super.noSuchMethod(
        Invocation.getter(#height),
        returnValue: 0.0,
      ) as double);

  @override
  set height(double? _height) => super.noSuchMethod(
        Invocation.setter(
          #height,
          _height,
        ),
        returnValueForMissingStub: null,
      );

  @override
  double get angle => (super.noSuchMethod(
        Invocation.getter(#angle),
        returnValue: 0.0,
      ) as double);

  @override
  set angle(double? _angle) => super.noSuchMethod(
        Invocation.setter(
          #angle,
          _angle,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i18.BoundingBoxAction get currentAction => (super.noSuchMethod(
        Invocation.getter(#currentAction),
        returnValue: _i18.BoundingBoxAction.none,
      ) as _i18.BoundingBoxAction);

  @override
  set currentAction(_i18.BoundingBoxAction? _currentAction) =>
      super.noSuchMethod(
        Invocation.setter(
          #currentAction,
          _currentAction,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i19.BoundingBoxResizeAction get currentBoundingBoxResizeAction =>
      (super.noSuchMethod(
        Invocation.getter(#currentBoundingBoxResizeAction),
        returnValue: _i19.BoundingBoxResizeAction.none,
      ) as _i19.BoundingBoxResizeAction);

  @override
  set currentBoundingBoxResizeAction(
          _i19.BoundingBoxResizeAction? _currentBoundingBoxResizeAction) =>
      super.noSuchMethod(
        Invocation.setter(
          #currentBoundingBoxResizeAction,
          _currentBoundingBoxResizeAction,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set lastDragGlobalPosition(_i2.Offset? _lastDragGlobalPosition) =>
      super.noSuchMethod(
        Invocation.setter(
          #lastDragGlobalPosition,
          _lastDragGlobalPosition,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set dragStartLocalPosition(_i2.Offset? _dragStartLocalPosition) =>
      super.noSuchMethod(
        Invocation.setter(
          #dragStartLocalPosition,
          _dragStartLocalPosition,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get activeRotationArcIndex => (super.noSuchMethod(
        Invocation.getter(#activeRotationArcIndex),
        returnValue: 0,
      ) as int);

  @override
  set activeRotationArcIndex(int? _activeRotationArcIndex) =>
      super.noSuchMethod(
        Invocation.setter(
          #activeRotationArcIndex,
          _activeRotationArcIndex,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Paint get boxPaint => (super.noSuchMethod(
        Invocation.getter(#boxPaint),
        returnValue: _i20.dummyValue<_i2.Paint>(
          this,
          Invocation.getter(#boxPaint),
        ),
      ) as _i2.Paint);

  @override
  set boxPaint(_i2.Paint? _boxPaint) => super.noSuchMethod(
        Invocation.setter(
          #boxPaint,
          _boxPaint,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Paint get handlePaint => (super.noSuchMethod(
        Invocation.getter(#handlePaint),
        returnValue: _i20.dummyValue<_i2.Paint>(
          this,
          Invocation.getter(#handlePaint),
        ),
      ) as _i2.Paint);

  @override
  set handlePaint(_i2.Paint? _handlePaint) => super.noSuchMethod(
        Invocation.setter(
          #handlePaint,
          _handlePaint,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Paint get rotationHandlePaint => (super.noSuchMethod(
        Invocation.getter(#rotationHandlePaint),
        returnValue: _i20.dummyValue<_i2.Paint>(
          this,
          Invocation.getter(#rotationHandlePaint),
        ),
      ) as _i2.Paint);

  @override
  set rotationHandlePaint(_i2.Paint? _rotationHandlePaint) =>
      super.noSuchMethod(
        Invocation.setter(
          #rotationHandlePaint,
          _rotationHandlePaint,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get isAspectRatioLocked => (super.noSuchMethod(
        Invocation.getter(#isAspectRatioLocked),
        returnValue: false,
      ) as bool);

  @override
  set isAspectRatioLocked(bool? _isAspectRatioLocked) => super.noSuchMethod(
        Invocation.setter(
          #isAspectRatioLocked,
          _isAspectRatioLocked,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Rect get rect => (super.noSuchMethod(
        Invocation.getter(#rect),
        returnValue: _FakeRect_1(
          this,
          Invocation.getter(#rect),
        ),
      ) as _i2.Rect);

  @override
  List<_i2.Offset> getCorners() => (super.noSuchMethod(
        Invocation.method(
          #getCorners,
          [],
        ),
        returnValue: <_i2.Offset>[],
      ) as List<_i2.Offset>);

  @override
  void determineAction(_i2.Offset? globalPoint) => super.noSuchMethod(
        Invocation.method(
          #determineAction,
          [globalPoint],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateDrag(_i2.Offset? globalPoint) => super.noSuchMethod(
        Invocation.method(
          #updateDrag,
          [globalPoint],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void endDrag() => super.noSuchMethod(
        Invocation.method(
          #endDrag,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawGuides(_i2.Canvas? canvas) => super.noSuchMethod(
        Invocation.method(
          #drawGuides,
          [canvas],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [CommandManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommandManager extends _i1.Mock implements _i21.CommandManager {
  MockCommandManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.Command> get redoStack => (super.noSuchMethod(
        Invocation.getter(#redoStack),
        returnValue: <_i3.Command>[],
      ) as List<_i3.Command>);

  @override
  List<_i3.Command> get undoStack => (super.noSuchMethod(
        Invocation.getter(#undoStack),
        returnValue: <_i3.Command>[],
      ) as List<_i3.Command>);

  @override
  void addGraphicCommand(_i22.GraphicCommand? command) => super.noSuchMethod(
        Invocation.method(
          #addGraphicCommand,
          [command],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setUndoStack(List<_i3.Command>? commands) => super.noSuchMethod(
        Invocation.method(
          #setUndoStack,
          [commands],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void executeLastCommand(_i2.Canvas? canvas) => super.noSuchMethod(
        Invocation.method(
          #executeLastCommand,
          [canvas],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void executeAllCommands(_i2.Canvas? canvas) => super.noSuchMethod(
        Invocation.method(
          #executeAllCommands,
          [canvas],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void discardLastCommand() => super.noSuchMethod(
        Invocation.method(
          #discardLastCommand,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearUndoStack({Iterable<_i3.Command>? newCommands}) =>
      super.noSuchMethod(
        Invocation.method(
          #clearUndoStack,
          [],
          {#newCommands: newCommands},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearRedoStack() => super.noSuchMethod(
        Invocation.method(
          #clearRedoStack,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawLineToolGhostPaths(
    _i2.Canvas? canvas,
    _i6.LineCommand? ingoingGhostPathCommand,
    _i6.LineCommand? outgoingGhostPathCommand,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #drawLineToolGhostPaths,
          [
            canvas,
            ingoingGhostPathCommand,
            outgoingGhostPathCommand,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawLineToolVertices(
    _i2.Canvas? canvas,
    _i23.VertexStack? vertexStack,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #drawLineToolVertices,
          [
            canvas,
            vertexStack,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Command redo() => (super.noSuchMethod(
        Invocation.method(
          #redo,
          [],
        ),
        returnValue: _FakeCommand_2(
          this,
          Invocation.method(
            #redo,
            [],
          ),
        ),
      ) as _i3.Command);

  @override
  void undo() => super.noSuchMethod(
        Invocation.method(
          #undo,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.ToolData getNextTool(_i21.ActionType? actionType) => (super.noSuchMethod(
        Invocation.method(
          #getNextTool,
          [actionType],
        ),
        returnValue: _FakeToolData_3(
          this,
          Invocation.method(
            #getNextTool,
            [actionType],
          ),
        ),
      ) as _i4.ToolData);

  @override
  List<_i6.LineCommand> getTopLineCommandSequence() => (super.noSuchMethod(
        Invocation.method(
          #getTopLineCommandSequence,
          [],
        ),
        returnValue: <_i6.LineCommand>[],
      ) as List<_i6.LineCommand>);
}

/// A class which mocks [CommandFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommandFactory extends _i1.Mock implements _i24.CommandFactory {
  MockCommandFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.PathCommand createPathCommand(
    _i25.PathWithActionHistory? path,
    _i2.Paint? paint, {
    bool? isCursor = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPathCommand,
          [
            path,
            paint,
          ],
          {#isCursor: isCursor},
        ),
        returnValue: _FakePathCommand_4(
          this,
          Invocation.method(
            #createPathCommand,
            [
              path,
              paint,
            ],
            {#isCursor: isCursor},
          ),
        ),
      ) as _i5.PathCommand);

  @override
  _i6.LineCommand createLineCommand(
    _i25.PathWithActionHistory? path,
    _i2.Paint? paint,
    _i2.Offset? startPoint,
    _i2.Offset? endPoint,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createLineCommand,
          [
            path,
            paint,
            startPoint,
            endPoint,
          ],
        ),
        returnValue: _FakeLineCommand_5(
          this,
          Invocation.method(
            #createLineCommand,
            [
              path,
              paint,
              startPoint,
              endPoint,
            ],
          ),
        ),
      ) as _i6.LineCommand);

  @override
  _i7.SquareShapeCommand createSquareShapeCommand(
    _i2.Paint? paint,
    _i2.Offset? topLeft,
    _i2.Offset? topRight,
    _i2.Offset? bottomLeft,
    _i2.Offset? bottomRight,
    _i26.ShapeStyle? style,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSquareShapeCommand,
          [
            paint,
            topLeft,
            topRight,
            bottomLeft,
            bottomRight,
            style,
          ],
        ),
        returnValue: _FakeSquareShapeCommand_6(
          this,
          Invocation.method(
            #createSquareShapeCommand,
            [
              paint,
              topLeft,
              topRight,
              bottomLeft,
              bottomRight,
              style,
            ],
          ),
        ),
      ) as _i7.SquareShapeCommand);

  @override
  _i8.EllipseShapeCommand createEllipseShapeCommand(
    _i2.Paint? paint,
    double? radiusX,
    double? radiusY,
    _i2.Offset? center,
    _i26.ShapeStyle? style,
    double? angle,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createEllipseShapeCommand,
          [
            paint,
            radiusX,
            radiusY,
            center,
            style,
            angle,
          ],
        ),
        returnValue: _FakeEllipseShapeCommand_7(
          this,
          Invocation.method(
            #createEllipseShapeCommand,
            [
              paint,
              radiusX,
              radiusY,
              center,
              style,
              angle,
            ],
          ),
        ),
      ) as _i8.EllipseShapeCommand);

  @override
  _i9.ClipboardCommand createClipboardCommand(
    _i2.Paint? paint,
    _i27.Uint8List? imageData,
    _i2.Offset? offset,
    double? scale,
    double? rotation,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createClipboardCommand,
          [
            paint,
            imageData,
            offset,
            scale,
            rotation,
          ],
        ),
        returnValue: _FakeClipboardCommand_8(
          this,
          Invocation.method(
            #createClipboardCommand,
            [
              paint,
              imageData,
              offset,
              scale,
              rotation,
            ],
          ),
        ),
      ) as _i9.ClipboardCommand);

  @override
  _i10.TextCommand createTextCommand(
    _i2.Offset? point,
    String? text,
    _i28.TextStyle? style,
    double? fontSize,
    _i2.Paint? paint,
    double? rotationAngle, {
    double? scaleX = 1.0,
    double? scaleY = 1.0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTextCommand,
          [
            point,
            text,
            style,
            fontSize,
            paint,
            rotationAngle,
          ],
          {
            #scaleX: scaleX,
            #scaleY: scaleY,
          },
        ),
        returnValue: _FakeTextCommand_9(
          this,
          Invocation.method(
            #createTextCommand,
            [
              point,
              text,
              style,
              fontSize,
              paint,
              rotationAngle,
            ],
            {
              #scaleX: scaleX,
              #scaleY: scaleY,
            },
          ),
        ),
      ) as _i10.TextCommand);

  @override
  _i11.StarShapeCommand createStarShapeCommand(
    _i2.Paint? paint,
    int? numPoints,
    double? angle,
    _i2.Offset? center,
    _i26.ShapeStyle? style,
    double? radiusX,
    double? radiusY,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createStarShapeCommand,
          [
            paint,
            numPoints,
            angle,
            center,
            style,
            radiusX,
            radiusY,
          ],
        ),
        returnValue: _FakeStarShapeCommand_10(
          this,
          Invocation.method(
            #createStarShapeCommand,
            [
              paint,
              numPoints,
              angle,
              center,
              style,
              radiusX,
              radiusY,
            ],
          ),
        ),
      ) as _i11.StarShapeCommand);

  @override
  _i12.HeartShapeCommand createHeartShapeCommand(
    _i2.Paint? paint,
    double? width,
    double? height,
    double? angle,
    _i2.Offset? center,
    _i26.ShapeStyle? style,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createHeartShapeCommand,
          [
            paint,
            width,
            height,
            angle,
            center,
            style,
          ],
        ),
        returnValue: _FakeHeartShapeCommand_11(
          this,
          Invocation.method(
            #createHeartShapeCommand,
            [
              paint,
              width,
              height,
              angle,
              center,
              style,
            ],
          ),
        ),
      ) as _i12.HeartShapeCommand);

  @override
  _i13.SprayCommand createSprayCommand(
    List<_i2.Offset>? points,
    _i2.Paint? paint,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSprayCommand,
          [
            points,
            paint,
          ],
        ),
        returnValue: _FakeSprayCommand_12(
          this,
          Invocation.method(
            #createSprayCommand,
            [
              points,
              paint,
            ],
          ),
        ),
      ) as _i13.SprayCommand);

  @override
  _i14.DeleteRegionCommand createDeleteRegionCommand(_i2.Rect? region) =>
      (super.noSuchMethod(
        Invocation.method(
          #createDeleteRegionCommand,
          [region],
        ),
        returnValue: _FakeDeleteRegionCommand_13(
          this,
          Invocation.method(
            #createDeleteRegionCommand,
            [region],
          ),
        ),
      ) as _i14.DeleteRegionCommand);

  @override
  _i15.ColorChangedCommand createColorChangedCommand(
    _i2.Color? oldColor,
    _i2.Color? newColor,
    _i2.Paint? paint,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createColorChangedCommand,
          [
            oldColor,
            newColor,
            paint,
          ],
        ),
        returnValue: _FakeColorChangedCommand_14(
          this,
          Invocation.method(
            #createColorChangedCommand,
            [
              oldColor,
              newColor,
              paint,
            ],
          ),
        ),
      ) as _i15.ColorChangedCommand);
}

/// A class which mocks [ClipboardCommand].
///
/// See the documentation for Mockito's code generation for more information.
class MockClipboardCommand extends _i1.Mock implements _i9.ClipboardCommand {
  MockClipboardCommand() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i27.Uint8List get imageData => (super.noSuchMethod(
        Invocation.getter(#imageData),
        returnValue: _i27.Uint8List(0),
      ) as _i27.Uint8List);

  @override
  _i2.Offset get offset => (super.noSuchMethod(
        Invocation.getter(#offset),
        returnValue: _FakeOffset_0(
          this,
          Invocation.getter(#offset),
        ),
      ) as _i2.Offset);

  @override
  double get scale => (super.noSuchMethod(
        Invocation.getter(#scale),
        returnValue: 0.0,
      ) as double);

  @override
  double get rotation => (super.noSuchMethod(
        Invocation.getter(#rotation),
        returnValue: 0.0,
      ) as double);

  @override
  int get version => (super.noSuchMethod(
        Invocation.getter(#version),
        returnValue: 0,
      ) as int);

  @override
  String get type => (super.noSuchMethod(
        Invocation.getter(#type),
        returnValue: _i20.dummyValue<String>(
          this,
          Invocation.getter(#type),
        ),
      ) as String);

  @override
  List<Object?> get props => (super.noSuchMethod(
        Invocation.getter(#props),
        returnValue: <Object?>[],
      ) as List<Object?>);

  @override
  _i2.Paint get paint => (super.noSuchMethod(
        Invocation.getter(#paint),
        returnValue: _i20.dummyValue<_i2.Paint>(
          this,
          Invocation.getter(#paint),
        ),
      ) as _i2.Paint);

  @override
  _i16.Logger get logger => (super.noSuchMethod(
        Invocation.getter(#logger),
        returnValue: _FakeLogger_15(
          this,
          Invocation.getter(#logger),
        ),
      ) as _i16.Logger);

  @override
  _i29.Future<void> prepareForRuntime() => (super.noSuchMethod(
        Invocation.method(
          #prepareForRuntime,
          [],
        ),
        returnValue: _i29.Future<void>.value(),
        returnValueForMissingStub: _i29.Future<void>.value(),
      ) as _i29.Future<void>);

  @override
  void call(_i2.Canvas? canvas) => super.noSuchMethod(
        Invocation.method(
          #call,
          [canvas],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}

/// A class which mocks [Image].
///
/// See the documentation for Mockito's code generation for more information.
class MockImage extends _i1.Mock implements _i2.Image {
  MockImage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get width => (super.noSuchMethod(
        Invocation.getter(#width),
        returnValue: 0,
      ) as int);

  @override
  int get height => (super.noSuchMethod(
        Invocation.getter(#height),
        returnValue: 0,
      ) as int);

  @override
  bool get debugDisposed => (super.noSuchMethod(
        Invocation.getter(#debugDisposed),
        returnValue: false,
      ) as bool);

  @override
  _i2.ColorSpace get colorSpace => (super.noSuchMethod(
        Invocation.getter(#colorSpace),
        returnValue: _i2.ColorSpace.sRGB,
      ) as _i2.ColorSpace);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i29.Future<_i27.ByteData?> toByteData(
          {_i2.ImageByteFormat? format = _i2.ImageByteFormat.rawRgba}) =>
      (super.noSuchMethod(
        Invocation.method(
          #toByteData,
          [],
          {#format: format},
        ),
        returnValue: _i29.Future<_i27.ByteData?>.value(),
      ) as _i29.Future<_i27.ByteData?>);

  @override
  _i2.Image clone() => (super.noSuchMethod(
        Invocation.method(
          #clone,
          [],
        ),
        returnValue: _FakeImage_16(
          this,
          Invocation.method(
            #clone,
            [],
          ),
        ),
      ) as _i2.Image);

  @override
  bool isCloneOf(_i2.Image? other) => (super.noSuchMethod(
        Invocation.method(
          #isCloneOf,
          [other],
        ),
        returnValue: false,
      ) as bool);
}
