// Mocks generated by Mockito 5.4.4 from annotations
// in paintroid/test/unit/tools/clipping_tool_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i30;
import 'dart:typed_data' as _i26;
import 'dart:ui' as _i17;

import 'package:flutter/material.dart' as _i27;
import 'package:logging/logging.dart' as _i20;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i29;
import 'package:paintroid/core/commands/command_factory/command_factory.dart'
    as _i24;
import 'package:paintroid/core/commands/command_implementation/command.dart'
    as _i2;
import 'package:paintroid/core/commands/command_implementation/graphic/clip_area_command.dart'
    as _i14;
import 'package:paintroid/core/commands/command_implementation/graphic/clipboard_command.dart'
    as _i8;
import 'package:paintroid/core/commands/command_implementation/graphic/color_changed_command.dart'
    as _i15;
import 'package:paintroid/core/commands/command_implementation/graphic/delete_region_command.dart'
    as _i13;
import 'package:paintroid/core/commands/command_implementation/graphic/graphic_command.dart'
    as _i22;
import 'package:paintroid/core/commands/command_implementation/graphic/line_command.dart'
    as _i5;
import 'package:paintroid/core/commands/command_implementation/graphic/path_command.dart'
    as _i4;
import 'package:paintroid/core/commands/command_implementation/graphic/shape/ellipse_shape_command.dart'
    as _i7;
import 'package:paintroid/core/commands/command_implementation/graphic/shape/heart_shape_command.dart'
    as _i11;
import 'package:paintroid/core/commands/command_implementation/graphic/shape/square_shape_command.dart'
    as _i6;
import 'package:paintroid/core/commands/command_implementation/graphic/shape/star_shape_command.dart'
    as _i10;
import 'package:paintroid/core/commands/command_implementation/graphic/spray_command.dart'
    as _i12;
import 'package:paintroid/core/commands/command_implementation/graphic/text_command.dart'
    as _i9;
import 'package:paintroid/core/commands/command_manager/command_manager.dart'
    as _i21;
import 'package:paintroid/core/commands/graphic_factory/graphic_factory.dart'
    as _i28;
import 'package:paintroid/core/commands/path_with_action_history.dart' as _i16;
import 'package:paintroid/core/enums/shape_style.dart' as _i25;
import 'package:paintroid/core/providers/object/tools/clipping_tool_state_provider.dart'
    as _i32;
import 'package:paintroid/core/providers/state/canvas_state_data.dart' as _i18;
import 'package:paintroid/core/providers/state/canvas_state_provider.dart'
    as _i31;
import 'package:paintroid/core/tools/line_tool/vertex_stack.dart' as _i23;
import 'package:paintroid/core/tools/tool_data.dart' as _i3;
import 'package:riverpod_annotation/riverpod_annotation.dart' as _i19;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCommand_0 extends _i1.SmartFake implements _i2.Command {
  _FakeCommand_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeToolData_1 extends _i1.SmartFake implements _i3.ToolData {
  _FakeToolData_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePathCommand_2 extends _i1.SmartFake implements _i4.PathCommand {
  _FakePathCommand_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLineCommand_3 extends _i1.SmartFake implements _i5.LineCommand {
  _FakeLineCommand_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSquareShapeCommand_4 extends _i1.SmartFake
    implements _i6.SquareShapeCommand {
  _FakeSquareShapeCommand_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEllipseShapeCommand_5 extends _i1.SmartFake
    implements _i7.EllipseShapeCommand {
  _FakeEllipseShapeCommand_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClipboardCommand_6 extends _i1.SmartFake
    implements _i8.ClipboardCommand {
  _FakeClipboardCommand_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTextCommand_7 extends _i1.SmartFake implements _i9.TextCommand {
  _FakeTextCommand_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStarShapeCommand_8 extends _i1.SmartFake
    implements _i10.StarShapeCommand {
  _FakeStarShapeCommand_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHeartShapeCommand_9 extends _i1.SmartFake
    implements _i11.HeartShapeCommand {
  _FakeHeartShapeCommand_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSprayCommand_10 extends _i1.SmartFake implements _i12.SprayCommand {
  _FakeSprayCommand_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeleteRegionCommand_11 extends _i1.SmartFake
    implements _i13.DeleteRegionCommand {
  _FakeDeleteRegionCommand_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClipAreaCommand_12 extends _i1.SmartFake
    implements _i14.ClipAreaCommand {
  _FakeClipAreaCommand_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeColorChangedCommand_13 extends _i1.SmartFake
    implements _i15.ColorChangedCommand {
  _FakeColorChangedCommand_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePathWithActionHistory_14 extends _i1.SmartFake
    implements _i16.PathWithActionHistory {
  _FakePathWithActionHistory_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePictureRecorder_15 extends _i1.SmartFake
    implements _i17.PictureRecorder {
  _FakePictureRecorder_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCanvas_16 extends _i1.SmartFake implements _i17.Canvas {
  _FakeCanvas_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSize_17 extends _i1.SmartFake implements _i17.Size {
  _FakeSize_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCanvasStateData_18 extends _i1.SmartFake
    implements _i18.CanvasStateData {
  _FakeCanvasStateData_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNotifierProviderRef_19<T> extends _i1.SmartFake
    implements _i19.NotifierProviderRef<T> {
  _FakeNotifierProviderRef_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLogger_20 extends _i1.SmartFake implements _i20.Logger {
  _FakeLogger_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAutoDisposeNotifierProviderRef_21<T> extends _i1.SmartFake
    implements _i19.AutoDisposeNotifierProviderRef<T> {
  _FakeAutoDisposeNotifierProviderRef_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePath_22 extends _i1.SmartFake implements _i17.Path {
  _FakePath_22(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CommandManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommandManager extends _i1.Mock implements _i21.CommandManager {
  MockCommandManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.Command> get redoStack => (super.noSuchMethod(
        Invocation.getter(#redoStack),
        returnValue: <_i2.Command>[],
      ) as List<_i2.Command>);

  @override
  List<_i2.Command> get undoStack => (super.noSuchMethod(
        Invocation.getter(#undoStack),
        returnValue: <_i2.Command>[],
      ) as List<_i2.Command>);

  @override
  void addGraphicCommand(_i22.GraphicCommand? command) => super.noSuchMethod(
        Invocation.method(
          #addGraphicCommand,
          [command],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeCommand(_i2.Command? commandToRemove) => super.noSuchMethod(
        Invocation.method(
          #removeCommand,
          [commandToRemove],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setUndoStack(List<_i2.Command>? commands) => super.noSuchMethod(
        Invocation.method(
          #setUndoStack,
          [commands],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void executeLastCommand(_i17.Canvas? canvas) => super.noSuchMethod(
        Invocation.method(
          #executeLastCommand,
          [canvas],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void executeAllCommands(_i17.Canvas? canvas) => super.noSuchMethod(
        Invocation.method(
          #executeAllCommands,
          [canvas],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void discardLastCommand() => super.noSuchMethod(
        Invocation.method(
          #discardLastCommand,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearUndoStack({Iterable<_i2.Command>? newCommands}) =>
      super.noSuchMethod(
        Invocation.method(
          #clearUndoStack,
          [],
          {#newCommands: newCommands},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearRedoStack() => super.noSuchMethod(
        Invocation.method(
          #clearRedoStack,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawLineToolGhostPaths(
    _i17.Canvas? canvas,
    _i5.LineCommand? ingoingGhostPathCommand,
    _i5.LineCommand? outgoingGhostPathCommand,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #drawLineToolGhostPaths,
          [
            canvas,
            ingoingGhostPathCommand,
            outgoingGhostPathCommand,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawLineToolVertices(
    _i17.Canvas? canvas,
    _i23.VertexStack? vertexStack,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #drawLineToolVertices,
          [
            canvas,
            vertexStack,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Command redo() => (super.noSuchMethod(
        Invocation.method(
          #redo,
          [],
        ),
        returnValue: _FakeCommand_0(
          this,
          Invocation.method(
            #redo,
            [],
          ),
        ),
      ) as _i2.Command);

  @override
  void undo() => super.noSuchMethod(
        Invocation.method(
          #undo,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.ToolData getNextTool(_i21.ActionType? actionType) => (super.noSuchMethod(
        Invocation.method(
          #getNextTool,
          [actionType],
        ),
        returnValue: _FakeToolData_1(
          this,
          Invocation.method(
            #getNextTool,
            [actionType],
          ),
        ),
      ) as _i3.ToolData);

  @override
  List<_i5.LineCommand> getTopLineCommandSequence() => (super.noSuchMethod(
        Invocation.method(
          #getTopLineCommandSequence,
          [],
        ),
        returnValue: <_i5.LineCommand>[],
      ) as List<_i5.LineCommand>);
}

/// A class which mocks [CommandFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommandFactory extends _i1.Mock implements _i24.CommandFactory {
  MockCommandFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.PathCommand createPathCommand(
    _i16.PathWithActionHistory? path,
    _i17.Paint? paint, {
    bool? isCursor = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPathCommand,
          [
            path,
            paint,
          ],
          {#isCursor: isCursor},
        ),
        returnValue: _FakePathCommand_2(
          this,
          Invocation.method(
            #createPathCommand,
            [
              path,
              paint,
            ],
            {#isCursor: isCursor},
          ),
        ),
      ) as _i4.PathCommand);

  @override
  _i5.LineCommand createLineCommand(
    _i16.PathWithActionHistory? path,
    _i17.Paint? paint,
    _i17.Offset? startPoint,
    _i17.Offset? endPoint,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createLineCommand,
          [
            path,
            paint,
            startPoint,
            endPoint,
          ],
        ),
        returnValue: _FakeLineCommand_3(
          this,
          Invocation.method(
            #createLineCommand,
            [
              path,
              paint,
              startPoint,
              endPoint,
            ],
          ),
        ),
      ) as _i5.LineCommand);

  @override
  _i6.SquareShapeCommand createSquareShapeCommand(
    _i17.Paint? paint,
    _i17.Offset? topLeft,
    _i17.Offset? topRight,
    _i17.Offset? bottomLeft,
    _i17.Offset? bottomRight,
    _i25.ShapeStyle? style,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSquareShapeCommand,
          [
            paint,
            topLeft,
            topRight,
            bottomLeft,
            bottomRight,
            style,
          ],
        ),
        returnValue: _FakeSquareShapeCommand_4(
          this,
          Invocation.method(
            #createSquareShapeCommand,
            [
              paint,
              topLeft,
              topRight,
              bottomLeft,
              bottomRight,
              style,
            ],
          ),
        ),
      ) as _i6.SquareShapeCommand);

  @override
  _i7.EllipseShapeCommand createEllipseShapeCommand(
    _i17.Paint? paint,
    double? radiusX,
    double? radiusY,
    _i17.Offset? center,
    _i25.ShapeStyle? style,
    double? angle,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createEllipseShapeCommand,
          [
            paint,
            radiusX,
            radiusY,
            center,
            style,
            angle,
          ],
        ),
        returnValue: _FakeEllipseShapeCommand_5(
          this,
          Invocation.method(
            #createEllipseShapeCommand,
            [
              paint,
              radiusX,
              radiusY,
              center,
              style,
              angle,
            ],
          ),
        ),
      ) as _i7.EllipseShapeCommand);

  @override
  _i8.ClipboardCommand createClipboardCommand(
    _i17.Paint? paint,
    _i26.Uint8List? imageData,
    _i17.Offset? offset,
    double? scale,
    double? rotation,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createClipboardCommand,
          [
            paint,
            imageData,
            offset,
            scale,
            rotation,
          ],
        ),
        returnValue: _FakeClipboardCommand_6(
          this,
          Invocation.method(
            #createClipboardCommand,
            [
              paint,
              imageData,
              offset,
              scale,
              rotation,
            ],
          ),
        ),
      ) as _i8.ClipboardCommand);

  @override
  _i9.TextCommand createTextCommand(
    _i17.Offset? point,
    String? text,
    _i27.TextStyle? style,
    double? fontSize,
    _i17.Paint? paint,
    double? rotationAngle, {
    double? scaleX = 1.0,
    double? scaleY = 1.0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTextCommand,
          [
            point,
            text,
            style,
            fontSize,
            paint,
            rotationAngle,
          ],
          {
            #scaleX: scaleX,
            #scaleY: scaleY,
          },
        ),
        returnValue: _FakeTextCommand_7(
          this,
          Invocation.method(
            #createTextCommand,
            [
              point,
              text,
              style,
              fontSize,
              paint,
              rotationAngle,
            ],
            {
              #scaleX: scaleX,
              #scaleY: scaleY,
            },
          ),
        ),
      ) as _i9.TextCommand);

  @override
  _i10.StarShapeCommand createStarShapeCommand(
    _i17.Paint? paint,
    int? numPoints,
    double? angle,
    _i17.Offset? center,
    _i25.ShapeStyle? style,
    double? radiusX,
    double? radiusY,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createStarShapeCommand,
          [
            paint,
            numPoints,
            angle,
            center,
            style,
            radiusX,
            radiusY,
          ],
        ),
        returnValue: _FakeStarShapeCommand_8(
          this,
          Invocation.method(
            #createStarShapeCommand,
            [
              paint,
              numPoints,
              angle,
              center,
              style,
              radiusX,
              radiusY,
            ],
          ),
        ),
      ) as _i10.StarShapeCommand);

  @override
  _i11.HeartShapeCommand createHeartShapeCommand(
    _i17.Paint? paint,
    double? width,
    double? height,
    double? angle,
    _i17.Offset? center,
    _i25.ShapeStyle? style,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createHeartShapeCommand,
          [
            paint,
            width,
            height,
            angle,
            center,
            style,
          ],
        ),
        returnValue: _FakeHeartShapeCommand_9(
          this,
          Invocation.method(
            #createHeartShapeCommand,
            [
              paint,
              width,
              height,
              angle,
              center,
              style,
            ],
          ),
        ),
      ) as _i11.HeartShapeCommand);

  @override
  _i12.SprayCommand createSprayCommand(
    List<_i17.Offset>? points,
    _i17.Paint? paint,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSprayCommand,
          [
            points,
            paint,
          ],
        ),
        returnValue: _FakeSprayCommand_10(
          this,
          Invocation.method(
            #createSprayCommand,
            [
              points,
              paint,
            ],
          ),
        ),
      ) as _i12.SprayCommand);

  @override
  _i13.DeleteRegionCommand createDeleteRegionCommand(_i17.Rect? region) =>
      (super.noSuchMethod(
        Invocation.method(
          #createDeleteRegionCommand,
          [region],
        ),
        returnValue: _FakeDeleteRegionCommand_11(
          this,
          Invocation.method(
            #createDeleteRegionCommand,
            [region],
          ),
        ),
      ) as _i13.DeleteRegionCommand);

  @override
  _i14.ClipAreaCommand createClipAreaCommand(
    _i16.PathWithActionHistory? path,
    _i17.Paint? paint,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createClipAreaCommand,
          [
            path,
            paint,
          ],
        ),
        returnValue: _FakeClipAreaCommand_12(
          this,
          Invocation.method(
            #createClipAreaCommand,
            [
              path,
              paint,
            ],
          ),
        ),
      ) as _i14.ClipAreaCommand);

  @override
  _i15.ColorChangedCommand createColorChangedCommand(
    _i17.Color? oldColor,
    _i17.Color? newColor,
    _i17.Paint? paint,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createColorChangedCommand,
          [
            oldColor,
            newColor,
            paint,
          ],
        ),
        returnValue: _FakeColorChangedCommand_13(
          this,
          Invocation.method(
            #createColorChangedCommand,
            [
              oldColor,
              newColor,
              paint,
            ],
          ),
        ),
      ) as _i15.ColorChangedCommand);
}

/// A class which mocks [GraphicFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockGraphicFactory extends _i1.Mock implements _i28.GraphicFactory {
  MockGraphicFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i17.Paint createPaint() => (super.noSuchMethod(
        Invocation.method(
          #createPaint,
          [],
        ),
        returnValue: _i29.dummyValue<_i17.Paint>(
          this,
          Invocation.method(
            #createPaint,
            [],
          ),
        ),
      ) as _i17.Paint);

  @override
  _i16.PathWithActionHistory createPathWithActionHistory() =>
      (super.noSuchMethod(
        Invocation.method(
          #createPathWithActionHistory,
          [],
        ),
        returnValue: _FakePathWithActionHistory_14(
          this,
          Invocation.method(
            #createPathWithActionHistory,
            [],
          ),
        ),
      ) as _i16.PathWithActionHistory);

  @override
  _i17.PictureRecorder createPictureRecorder() => (super.noSuchMethod(
        Invocation.method(
          #createPictureRecorder,
          [],
        ),
        returnValue: _FakePictureRecorder_15(
          this,
          Invocation.method(
            #createPictureRecorder,
            [],
          ),
        ),
      ) as _i17.PictureRecorder);

  @override
  _i17.Canvas createCanvasWithRecorder(_i17.PictureRecorder? recorder) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCanvasWithRecorder,
          [recorder],
        ),
        returnValue: _FakeCanvas_16(
          this,
          Invocation.method(
            #createCanvasWithRecorder,
            [recorder],
          ),
        ),
      ) as _i17.Canvas);

  @override
  _i17.Paint createWatercolorPaint(
    _i17.Paint? originalPaint,
    double? blurSigma,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createWatercolorPaint,
          [
            originalPaint,
            blurSigma,
          ],
        ),
        returnValue: _i29.dummyValue<_i17.Paint>(
          this,
          Invocation.method(
            #createWatercolorPaint,
            [
              originalPaint,
              blurSigma,
            ],
          ),
        ),
      ) as _i17.Paint);

  @override
  _i17.Paint copyPaint(_i17.Paint? original) => (super.noSuchMethod(
        Invocation.method(
          #copyPaint,
          [original],
        ),
        returnValue: _i29.dummyValue<_i17.Paint>(
          this,
          Invocation.method(
            #copyPaint,
            [original],
          ),
        ),
      ) as _i17.Paint);
}

/// A class which mocks [GraphicCommand].
///
/// See the documentation for Mockito's code generation for more information.
class MockGraphicCommand extends _i1.Mock implements _i22.GraphicCommand {
  MockGraphicCommand() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i17.Paint get paint => (super.noSuchMethod(
        Invocation.getter(#paint),
        returnValue: _i29.dummyValue<_i17.Paint>(
          this,
          Invocation.getter(#paint),
        ),
      ) as _i17.Paint);

  @override
  List<Object?> get props => (super.noSuchMethod(
        Invocation.getter(#props),
        returnValue: <Object?>[],
      ) as List<Object?>);

  @override
  void call(_i17.Canvas? canvas) => super.noSuchMethod(
        Invocation.method(
          #call,
          [canvas],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i30.Future<void> prepareForRuntime() => (super.noSuchMethod(
        Invocation.method(
          #prepareForRuntime,
          [],
        ),
        returnValue: _i30.Future<void>.value(),
        returnValueForMissingStub: _i30.Future<void>.value(),
      ) as _i30.Future<void>);
}

/// A class which mocks [CanvasStateProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockCanvasStateProvider extends _i1.Mock
    implements _i31.CanvasStateProvider {
  MockCanvasStateProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i17.Size get initialCanvasSize => (super.noSuchMethod(
        Invocation.getter(#initialCanvasSize),
        returnValue: _FakeSize_17(
          this,
          Invocation.getter(#initialCanvasSize),
        ),
      ) as _i17.Size);

  @override
  set initialCanvasSize(_i17.Size? _initialCanvasSize) => super.noSuchMethod(
        Invocation.setter(
          #initialCanvasSize,
          _initialCanvasSize,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i18.CanvasStateData get currentState => (super.noSuchMethod(
        Invocation.getter(#currentState),
        returnValue: _FakeCanvasStateData_18(
          this,
          Invocation.getter(#currentState),
        ),
      ) as _i18.CanvasStateData);

  @override
  _i19.NotifierProviderRef<_i18.CanvasStateData> get ref => (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue: _FakeNotifierProviderRef_19<_i18.CanvasStateData>(
          this,
          Invocation.getter(#ref),
        ),
      ) as _i19.NotifierProviderRef<_i18.CanvasStateData>);

  @override
  _i18.CanvasStateData get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeCanvasStateData_18(
          this,
          Invocation.getter(#state),
        ),
      ) as _i18.CanvasStateData);

  @override
  set state(_i18.CanvasStateData? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i20.Logger get logger => (super.noSuchMethod(
        Invocation.getter(#logger),
        returnValue: _FakeLogger_20(
          this,
          Invocation.getter(#logger),
        ),
      ) as _i20.Logger);

  @override
  void requestResetView() => super.noSuchMethod(
        Invocation.method(
          #requestResetView,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i18.CanvasStateData build() => (super.noSuchMethod(
        Invocation.method(
          #build,
          [],
        ),
        returnValue: _FakeCanvasStateData_18(
          this,
          Invocation.method(
            #build,
            [],
          ),
        ),
      ) as _i18.CanvasStateData);

  @override
  void setBackgroundImage(_i17.Image? image) => super.noSuchMethod(
        Invocation.method(
          #setBackgroundImage,
          [image],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearBackgroundImageAndResetDimensions() => super.noSuchMethod(
        Invocation.method(
          #clearBackgroundImageAndResetDimensions,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i30.Future<void> updateCachedImage() => (super.noSuchMethod(
        Invocation.method(
          #updateCachedImage,
          [],
        ),
        returnValue: _i30.Future<void>.value(),
        returnValueForMissingStub: _i30.Future<void>.value(),
      ) as _i30.Future<void>);

  @override
  _i30.Future<void> resetCanvasWithNewCommands(
          Iterable<_i2.Command>? commands) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetCanvasWithNewCommands,
          [commands],
        ),
        returnValue: _i30.Future<void>.value(),
        returnValueForMissingStub: _i30.Future<void>.value(),
      ) as _i30.Future<void>);

  @override
  _i30.Future<void> resetCanvasWithExistingCommands() => (super.noSuchMethod(
        Invocation.method(
          #resetCanvasWithExistingCommands,
          [],
        ),
        returnValue: _i30.Future<void>.value(),
        returnValueForMissingStub: _i30.Future<void>.value(),
      ) as _i30.Future<void>);

  @override
  void listenSelf(
    void Function(
      _i18.CanvasStateData?,
      _i18.CanvasStateData,
    )? listener, {
    void Function(
      Object,
      StackTrace,
    )? onError,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #listenSelf,
          [listener],
          {#onError: onError},
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool updateShouldNotify(
    _i18.CanvasStateData? previous,
    _i18.CanvasStateData? next,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            previous,
            next,
          ],
        ),
        returnValue: false,
      ) as bool);
}

/// A class which mocks [ClippingToolState].
///
/// See the documentation for Mockito's code generation for more information.
class MockClippingToolState extends _i1.Mock implements _i32.ClippingToolState {
  MockClippingToolState() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get hasActiveClipPath => (super.noSuchMethod(
        Invocation.getter(#hasActiveClipPath),
        returnValue: false,
      ) as bool);

  @override
  _i19.AutoDisposeNotifierProviderRef<bool> get ref => (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue: _FakeAutoDisposeNotifierProviderRef_21<bool>(
          this,
          Invocation.getter(#ref),
        ),
      ) as _i19.AutoDisposeNotifierProviderRef<bool>);

  @override
  bool get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: false,
      ) as bool);

  @override
  set state(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool build() => (super.noSuchMethod(
        Invocation.method(
          #build,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  void setHasActiveClipPath(bool? hasActive) => super.noSuchMethod(
        Invocation.method(
          #setHasActiveClipPath,
          [hasActive],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearClipPath() => super.noSuchMethod(
        Invocation.method(
          #clearClipPath,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void listenSelf(
    void Function(
      bool?,
      bool,
    )? listener, {
    void Function(
      Object,
      StackTrace,
    )? onError,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #listenSelf,
          [listener],
          {#onError: onError},
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool updateShouldNotify(
    bool? previous,
    bool? next,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            previous,
            next,
          ],
        ),
        returnValue: false,
      ) as bool);
}

/// A class which mocks [PathWithActionHistory].
///
/// See the documentation for Mockito's code generation for more information.
class MockPathWithActionHistory extends _i1.Mock
    implements _i16.PathWithActionHistory {
  MockPathWithActionHistory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i17.Path get path => (super.noSuchMethod(
        Invocation.getter(#path),
        returnValue: _FakePath_22(
          this,
          Invocation.getter(#path),
        ),
      ) as _i17.Path);

  @override
  List<_i16.PathAction> get actions => (super.noSuchMethod(
        Invocation.getter(#actions),
        returnValue: <_i16.PathAction>[],
      ) as List<_i16.PathAction>);

  @override
  void moveTo(
    double? x,
    double? y,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #moveTo,
          [
            x,
            y,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void lineTo(
    double? x,
    double? y,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #lineTo,
          [
            x,
            y,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}

/// A class which mocks [ClipAreaCommand].
///
/// See the documentation for Mockito's code generation for more information.
class MockClipAreaCommand extends _i1.Mock implements _i14.ClipAreaCommand {
  MockClipAreaCommand() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get type => (super.noSuchMethod(
        Invocation.getter(#type),
        returnValue: _i29.dummyValue<String>(
          this,
          Invocation.getter(#type),
        ),
      ) as String);

  @override
  int get version => (super.noSuchMethod(
        Invocation.getter(#version),
        returnValue: 0,
      ) as int);

  @override
  _i16.PathWithActionHistory get clipPathData => (super.noSuchMethod(
        Invocation.getter(#clipPathData),
        returnValue: _FakePathWithActionHistory_14(
          this,
          Invocation.getter(#clipPathData),
        ),
      ) as _i16.PathWithActionHistory);

  @override
  List<Object?> get props => (super.noSuchMethod(
        Invocation.getter(#props),
        returnValue: <Object?>[],
      ) as List<Object?>);

  @override
  _i17.Paint get paint => (super.noSuchMethod(
        Invocation.getter(#paint),
        returnValue: _i29.dummyValue<_i17.Paint>(
          this,
          Invocation.getter(#paint),
        ),
      ) as _i17.Paint);

  @override
  void call(_i17.Canvas? canvas) => super.noSuchMethod(
        Invocation.method(
          #call,
          [canvas],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i30.Future<void> prepareForRuntime() => (super.noSuchMethod(
        Invocation.method(
          #prepareForRuntime,
          [],
        ),
        returnValue: _i30.Future<void>.value(),
        returnValueForMissingStub: _i30.Future<void>.value(),
      ) as _i30.Future<void>);
}
