// Mocks generated by Mockito 5.4.5 from annotations
// in paintroid/test/unit/tools/text_tool_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:typed_data' as _i19;
import 'dart:ui' as _i11;

import 'package:flutter/material.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i18;
import 'package:paintroid/core/commands/command_factory/command_factory.dart'
    as _i16;
import 'package:paintroid/core/commands/command_implementation/command.dart'
    as _i2;
import 'package:paintroid/core/commands/command_implementation/graphic/graphic_command.dart'
    as _i14;
import 'package:paintroid/core/commands/command_implementation/graphic/line_command.dart'
    as _i5;
import 'package:paintroid/core/commands/command_implementation/graphic/path_command.dart'
    as _i4;
import 'package:paintroid/core/commands/command_implementation/graphic/shape/circle_shape_command.dart'
    as _i7;
import 'package:paintroid/core/commands/command_implementation/graphic/shape/square_shape_command.dart'
    as _i6;
import 'package:paintroid/core/commands/command_implementation/graphic/spray_command.dart'
    as _i9;
import 'package:paintroid/core/commands/command_implementation/graphic/text_command.dart'
    as _i8;
import 'package:paintroid/core/commands/command_manager/command_manager.dart'
    as _i13;
import 'package:paintroid/core/commands/path_with_action_history.dart' as _i17;
import 'package:paintroid/core/enums/bounding_box_corners.dart' as _i21;
import 'package:paintroid/core/tools/bounding_box.dart' as _i20;
import 'package:paintroid/core/tools/line_tool/vertex_stack.dart' as _i15;
import 'package:paintroid/core/tools/tool_data.dart' as _i3;
import 'package:riverpod/src/internals.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCommand_0 extends _i1.SmartFake implements _i2.Command {
  _FakeCommand_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeToolData_1 extends _i1.SmartFake implements _i3.ToolData {
  _FakeToolData_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePathCommand_2 extends _i1.SmartFake implements _i4.PathCommand {
  _FakePathCommand_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLineCommand_3 extends _i1.SmartFake implements _i5.LineCommand {
  _FakeLineCommand_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSquareShapeCommand_4 extends _i1.SmartFake
    implements _i6.SquareShapeCommand {
  _FakeSquareShapeCommand_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCircleShapeCommand_5 extends _i1.SmartFake
    implements _i7.CircleShapeCommand {
  _FakeCircleShapeCommand_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTextCommand_6 extends _i1.SmartFake implements _i8.TextCommand {
  _FakeTextCommand_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSprayCommand_7 extends _i1.SmartFake implements _i9.SprayCommand {
  _FakeSprayCommand_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProviderContainer_8 extends _i1.SmartFake
    implements _i10.ProviderContainer {
  _FakeProviderContainer_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeKeepAliveLink_9 extends _i1.SmartFake implements _i10.KeepAliveLink {
  _FakeKeepAliveLink_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProviderSubscription_10<State1> extends _i1.SmartFake
    implements _i10.ProviderSubscription<State1> {
  _FakeProviderSubscription_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRect_11 extends _i1.SmartFake implements _i11.Rect {
  _FakeRect_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOffset_12 extends _i1.SmartFake implements _i11.Offset {
  _FakeOffset_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTextStyle_13 extends _i1.SmartFake implements _i12.TextStyle {
  _FakeTextStyle_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString(
          {_i12.DiagnosticLevel? minLevel = _i12.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakePath_14 extends _i1.SmartFake implements _i11.Path {
  _FakePath_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CommandManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommandManager extends _i1.Mock implements _i13.CommandManager {
  MockCommandManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.Command> get redoStack => (super.noSuchMethod(
        Invocation.getter(#redoStack),
        returnValue: <_i2.Command>[],
      ) as List<_i2.Command>);

  @override
  List<_i2.Command> get undoStack => (super.noSuchMethod(
        Invocation.getter(#undoStack),
        returnValue: <_i2.Command>[],
      ) as List<_i2.Command>);

  @override
  void addGraphicCommand(_i14.GraphicCommand? command) => super.noSuchMethod(
        Invocation.method(
          #addGraphicCommand,
          [command],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setUndoStack(List<_i2.Command>? commands) => super.noSuchMethod(
        Invocation.method(
          #setUndoStack,
          [commands],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void executeLastCommand(_i11.Canvas? canvas) => super.noSuchMethod(
        Invocation.method(
          #executeLastCommand,
          [canvas],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void executeAllCommands(_i11.Canvas? canvas) => super.noSuchMethod(
        Invocation.method(
          #executeAllCommands,
          [canvas],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void discardLastCommand() => super.noSuchMethod(
        Invocation.method(
          #discardLastCommand,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearUndoStack({Iterable<_i2.Command>? newCommands}) =>
      super.noSuchMethod(
        Invocation.method(
          #clearUndoStack,
          [],
          {#newCommands: newCommands},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearRedoStack() => super.noSuchMethod(
        Invocation.method(
          #clearRedoStack,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawLineToolGhostPaths(
    _i11.Canvas? canvas,
    _i5.LineCommand? ingoingGhostPathCommand,
    _i5.LineCommand? outgoingGhostPathCommand,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #drawLineToolGhostPaths,
          [
            canvas,
            ingoingGhostPathCommand,
            outgoingGhostPathCommand,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawLineToolVertices(
    _i11.Canvas? canvas,
    _i15.VertexStack? vertexStack,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #drawLineToolVertices,
          [
            canvas,
            vertexStack,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Command redo() => (super.noSuchMethod(
        Invocation.method(
          #redo,
          [],
        ),
        returnValue: _FakeCommand_0(
          this,
          Invocation.method(
            #redo,
            [],
          ),
        ),
      ) as _i2.Command);

  @override
  void undo() => super.noSuchMethod(
        Invocation.method(
          #undo,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.ToolData getNextTool(_i13.ActionType? actionType) => (super.noSuchMethod(
        Invocation.method(
          #getNextTool,
          [actionType],
        ),
        returnValue: _FakeToolData_1(
          this,
          Invocation.method(
            #getNextTool,
            [actionType],
          ),
        ),
      ) as _i3.ToolData);

  @override
  List<_i5.LineCommand> getTopLineCommandSequence() => (super.noSuchMethod(
        Invocation.method(
          #getTopLineCommandSequence,
          [],
        ),
        returnValue: <_i5.LineCommand>[],
      ) as List<_i5.LineCommand>);
}

/// A class which mocks [CommandFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommandFactory extends _i1.Mock implements _i16.CommandFactory {
  MockCommandFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.PathCommand createPathCommand(
    _i17.PathWithActionHistory? path,
    _i11.Paint? paint,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPathCommand,
          [
            path,
            paint,
          ],
        ),
        returnValue: _FakePathCommand_2(
          this,
          Invocation.method(
            #createPathCommand,
            [
              path,
              paint,
            ],
          ),
        ),
      ) as _i4.PathCommand);

  @override
  _i5.LineCommand createLineCommand(
    _i17.PathWithActionHistory? path,
    _i11.Paint? paint,
    _i11.Offset? startPoint,
    _i11.Offset? endPoint,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createLineCommand,
          [
            path,
            paint,
            startPoint,
            endPoint,
          ],
        ),
        returnValue: _FakeLineCommand_3(
          this,
          Invocation.method(
            #createLineCommand,
            [
              path,
              paint,
              startPoint,
              endPoint,
            ],
          ),
        ),
      ) as _i5.LineCommand);

  @override
  _i6.SquareShapeCommand createSquareShapeCommand(
    _i11.Paint? paint,
    _i11.Offset? topLeft,
    _i11.Offset? topRight,
    _i11.Offset? bottomLeft,
    _i11.Offset? bottomRight,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSquareShapeCommand,
          [
            paint,
            topLeft,
            topRight,
            bottomLeft,
            bottomRight,
          ],
        ),
        returnValue: _FakeSquareShapeCommand_4(
          this,
          Invocation.method(
            #createSquareShapeCommand,
            [
              paint,
              topLeft,
              topRight,
              bottomLeft,
              bottomRight,
            ],
          ),
        ),
      ) as _i6.SquareShapeCommand);

  @override
  _i7.CircleShapeCommand createCircleShapeCommand(
    _i11.Paint? paint,
    double? radius,
    _i11.Offset? center,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCircleShapeCommand,
          [
            paint,
            radius,
            center,
          ],
        ),
        returnValue: _FakeCircleShapeCommand_5(
          this,
          Invocation.method(
            #createCircleShapeCommand,
            [
              paint,
              radius,
              center,
            ],
          ),
        ),
      ) as _i7.CircleShapeCommand);

  @override
  _i8.TextCommand createTextCommand(
    _i11.Offset? point,
    String? text,
    _i12.TextStyle? style,
    double? fontSize,
    _i11.Paint? paint,
    double? rotationAngle,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTextCommand,
          [
            point,
            text,
            style,
            fontSize,
            paint,
            rotationAngle,
          ],
        ),
        returnValue: _FakeTextCommand_6(
          this,
          Invocation.method(
            #createTextCommand,
            [
              point,
              text,
              style,
              fontSize,
              paint,
              rotationAngle,
            ],
          ),
        ),
      ) as _i8.TextCommand);

  @override
  _i9.SprayCommand createSprayCommand(
    List<_i11.Offset>? points,
    _i11.Paint? paint,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSprayCommand,
          [
            points,
            paint,
          ],
        ),
        returnValue: _FakeSprayCommand_7(
          this,
          Invocation.method(
            #createSprayCommand,
            [
              points,
              paint,
            ],
          ),
        ),
      ) as _i9.SprayCommand);
}

/// A class which mocks [Ref].
///
/// See the documentation for Mockito's code generation for more information.
class MockRef<State extends Object?> extends _i1.Mock
    implements _i10.Ref<State> {
  MockRef() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.ProviderContainer get container => (super.noSuchMethod(
        Invocation.getter(#container),
        returnValue: _FakeProviderContainer_8(
          this,
          Invocation.getter(#container),
        ),
      ) as _i10.ProviderContainer);

  @override
  T refresh<T>(_i10.Refreshable<T>? provider) => (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [provider],
        ),
        returnValue: _i18.dummyValue<T>(
          this,
          Invocation.method(
            #refresh,
            [provider],
          ),
        ),
      ) as T);

  @override
  void invalidate(_i10.ProviderOrFamily? provider) => super.noSuchMethod(
        Invocation.method(
          #invalidate,
          [provider],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void listenSelf(
    void Function(
      State?,
      State,
    )? listener, {
    void Function(
      Object,
      StackTrace,
    )? onError,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #listenSelf,
          [listener],
          {#onError: onError},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void invalidateSelf() => super.noSuchMethod(
        Invocation.method(
          #invalidateSelf,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onAddListener(void Function()? cb) => super.noSuchMethod(
        Invocation.method(
          #onAddListener,
          [cb],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onRemoveListener(void Function()? cb) => super.noSuchMethod(
        Invocation.method(
          #onRemoveListener,
          [cb],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onResume(void Function()? cb) => super.noSuchMethod(
        Invocation.method(
          #onResume,
          [cb],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onCancel(void Function()? cb) => super.noSuchMethod(
        Invocation.method(
          #onCancel,
          [cb],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDispose(void Function()? cb) => super.noSuchMethod(
        Invocation.method(
          #onDispose,
          [cb],
        ),
        returnValueForMissingStub: null,
      );

  @override
  T read<T>(_i10.ProviderListenable<T>? provider) => (super.noSuchMethod(
        Invocation.method(
          #read,
          [provider],
        ),
        returnValue: _i18.dummyValue<T>(
          this,
          Invocation.method(
            #read,
            [provider],
          ),
        ),
      ) as T);

  @override
  bool exists(_i10.ProviderBase<Object?>? provider) => (super.noSuchMethod(
        Invocation.method(
          #exists,
          [provider],
        ),
        returnValue: false,
      ) as bool);

  @override
  T watch<T>(_i10.ProviderListenable<T>? provider) => (super.noSuchMethod(
        Invocation.method(
          #watch,
          [provider],
        ),
        returnValue: _i18.dummyValue<T>(
          this,
          Invocation.method(
            #watch,
            [provider],
          ),
        ),
      ) as T);

  @override
  _i10.KeepAliveLink keepAlive() => (super.noSuchMethod(
        Invocation.method(
          #keepAlive,
          [],
        ),
        returnValue: _FakeKeepAliveLink_9(
          this,
          Invocation.method(
            #keepAlive,
            [],
          ),
        ),
      ) as _i10.KeepAliveLink);

  @override
  _i10.ProviderSubscription<T> listen<T>(
    _i10.ProviderListenable<T>? provider,
    void Function(
      T?,
      T,
    )? listener, {
    void Function(
      Object,
      StackTrace,
    )? onError,
    bool? fireImmediately,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listen,
          [
            provider,
            listener,
          ],
          {
            #onError: onError,
            #fireImmediately: fireImmediately,
          },
        ),
        returnValue: _FakeProviderSubscription_10<T>(
          this,
          Invocation.method(
            #listen,
            [
              provider,
              listener,
            ],
            {
              #onError: onError,
              #fireImmediately: fireImmediately,
            },
          ),
        ),
      ) as _i10.ProviderSubscription<T>);
}

/// A class which mocks [Canvas].
///
/// See the documentation for Mockito's code generation for more information.
class MockCanvas extends _i1.Mock implements _i11.Canvas {
  MockCanvas() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void save() => super.noSuchMethod(
        Invocation.method(
          #save,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void saveLayer(
    _i11.Rect? bounds,
    _i11.Paint? paint,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #saveLayer,
          [
            bounds,
            paint,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void restore() => super.noSuchMethod(
        Invocation.method(
          #restore,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void restoreToCount(int? count) => super.noSuchMethod(
        Invocation.method(
          #restoreToCount,
          [count],
        ),
        returnValueForMissingStub: null,
      );

  @override
  int getSaveCount() => (super.noSuchMethod(
        Invocation.method(
          #getSaveCount,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  void translate(
    double? dx,
    double? dy,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #translate,
          [
            dx,
            dy,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void scale(
    double? sx, [
    double? sy,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #scale,
          [
            sx,
            sy,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void rotate(double? radians) => super.noSuchMethod(
        Invocation.method(
          #rotate,
          [radians],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void skew(
    double? sx,
    double? sy,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #skew,
          [
            sx,
            sy,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void transform(_i19.Float64List? matrix4) => super.noSuchMethod(
        Invocation.method(
          #transform,
          [matrix4],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i19.Float64List getTransform() => (super.noSuchMethod(
        Invocation.method(
          #getTransform,
          [],
        ),
        returnValue: _i19.Float64List(0),
      ) as _i19.Float64List);

  @override
  void clipRect(
    _i11.Rect? rect, {
    _i11.ClipOp? clipOp = _i11.ClipOp.intersect,
    bool? doAntiAlias = true,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #clipRect,
          [rect],
          {
            #clipOp: clipOp,
            #doAntiAlias: doAntiAlias,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clipRRect(
    _i11.RRect? rrect, {
    bool? doAntiAlias = true,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #clipRRect,
          [rrect],
          {#doAntiAlias: doAntiAlias},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clipPath(
    _i11.Path? path, {
    bool? doAntiAlias = true,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #clipPath,
          [path],
          {#doAntiAlias: doAntiAlias},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i11.Rect getLocalClipBounds() => (super.noSuchMethod(
        Invocation.method(
          #getLocalClipBounds,
          [],
        ),
        returnValue: _FakeRect_11(
          this,
          Invocation.method(
            #getLocalClipBounds,
            [],
          ),
        ),
      ) as _i11.Rect);

  @override
  _i11.Rect getDestinationClipBounds() => (super.noSuchMethod(
        Invocation.method(
          #getDestinationClipBounds,
          [],
        ),
        returnValue: _FakeRect_11(
          this,
          Invocation.method(
            #getDestinationClipBounds,
            [],
          ),
        ),
      ) as _i11.Rect);

  @override
  void drawColor(
    _i11.Color? color,
    _i11.BlendMode? blendMode,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #drawColor,
          [
            color,
            blendMode,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawLine(
    _i11.Offset? p1,
    _i11.Offset? p2,
    _i11.Paint? paint,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #drawLine,
          [
            p1,
            p2,
            paint,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawPaint(_i11.Paint? paint) => super.noSuchMethod(
        Invocation.method(
          #drawPaint,
          [paint],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawRect(
    _i11.Rect? rect,
    _i11.Paint? paint,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #drawRect,
          [
            rect,
            paint,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawRRect(
    _i11.RRect? rrect,
    _i11.Paint? paint,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #drawRRect,
          [
            rrect,
            paint,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawDRRect(
    _i11.RRect? outer,
    _i11.RRect? inner,
    _i11.Paint? paint,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #drawDRRect,
          [
            outer,
            inner,
            paint,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawOval(
    _i11.Rect? rect,
    _i11.Paint? paint,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #drawOval,
          [
            rect,
            paint,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawCircle(
    _i11.Offset? c,
    double? radius,
    _i11.Paint? paint,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #drawCircle,
          [
            c,
            radius,
            paint,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawArc(
    _i11.Rect? rect,
    double? startAngle,
    double? sweepAngle,
    bool? useCenter,
    _i11.Paint? paint,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #drawArc,
          [
            rect,
            startAngle,
            sweepAngle,
            useCenter,
            paint,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawPath(
    _i11.Path? path,
    _i11.Paint? paint,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #drawPath,
          [
            path,
            paint,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawImage(
    _i11.Image? image,
    _i11.Offset? offset,
    _i11.Paint? paint,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #drawImage,
          [
            image,
            offset,
            paint,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawImageRect(
    _i11.Image? image,
    _i11.Rect? src,
    _i11.Rect? dst,
    _i11.Paint? paint,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #drawImageRect,
          [
            image,
            src,
            dst,
            paint,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawImageNine(
    _i11.Image? image,
    _i11.Rect? center,
    _i11.Rect? dst,
    _i11.Paint? paint,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #drawImageNine,
          [
            image,
            center,
            dst,
            paint,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawPicture(_i11.Picture? picture) => super.noSuchMethod(
        Invocation.method(
          #drawPicture,
          [picture],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawParagraph(
    _i11.Paragraph? paragraph,
    _i11.Offset? offset,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #drawParagraph,
          [
            paragraph,
            offset,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawPoints(
    _i11.PointMode? pointMode,
    List<_i11.Offset>? points,
    _i11.Paint? paint,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #drawPoints,
          [
            pointMode,
            points,
            paint,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawRawPoints(
    _i11.PointMode? pointMode,
    _i19.Float32List? points,
    _i11.Paint? paint,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #drawRawPoints,
          [
            pointMode,
            points,
            paint,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawVertices(
    _i11.Vertices? vertices,
    _i11.BlendMode? blendMode,
    _i11.Paint? paint,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #drawVertices,
          [
            vertices,
            blendMode,
            paint,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawAtlas(
    _i11.Image? atlas,
    List<_i11.RSTransform>? transforms,
    List<_i11.Rect>? rects,
    List<_i11.Color>? colors,
    _i11.BlendMode? blendMode,
    _i11.Rect? cullRect,
    _i11.Paint? paint,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #drawAtlas,
          [
            atlas,
            transforms,
            rects,
            colors,
            blendMode,
            cullRect,
            paint,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawRawAtlas(
    _i11.Image? atlas,
    _i19.Float32List? rstTransforms,
    _i19.Float32List? rects,
    _i19.Int32List? colors,
    _i11.BlendMode? blendMode,
    _i11.Rect? cullRect,
    _i11.Paint? paint,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #drawRawAtlas,
          [
            atlas,
            rstTransforms,
            rects,
            colors,
            blendMode,
            cullRect,
            paint,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawShadow(
    _i11.Path? path,
    _i11.Color? color,
    double? elevation,
    bool? transparentOccluder,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #drawShadow,
          [
            path,
            color,
            elevation,
            transparentOccluder,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [TextCommand].
///
/// See the documentation for Mockito's code generation for more information.
class MockTextCommand extends _i1.Mock implements _i8.TextCommand {
  MockTextCommand() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Offset get point => (super.noSuchMethod(
        Invocation.getter(#point),
        returnValue: _FakeOffset_12(
          this,
          Invocation.getter(#point),
        ),
      ) as _i11.Offset);

  @override
  set point(_i11.Offset? _point) => super.noSuchMethod(
        Invocation.setter(
          #point,
          _point,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.TextStyle get style => (super.noSuchMethod(
        Invocation.getter(#style),
        returnValue: _FakeTextStyle_13(
          this,
          Invocation.getter(#style),
        ),
      ) as _i12.TextStyle);

  @override
  String get text => (super.noSuchMethod(
        Invocation.getter(#text),
        returnValue: _i18.dummyValue<String>(
          this,
          Invocation.getter(#text),
        ),
      ) as String);

  @override
  double get rotationAngle => (super.noSuchMethod(
        Invocation.getter(#rotationAngle),
        returnValue: 0.0,
      ) as double);

  @override
  int get version => (super.noSuchMethod(
        Invocation.getter(#version),
        returnValue: 0,
      ) as int);

  @override
  String get type => (super.noSuchMethod(
        Invocation.getter(#type),
        returnValue: _i18.dummyValue<String>(
          this,
          Invocation.getter(#type),
        ),
      ) as String);

  @override
  double get fontSize => (super.noSuchMethod(
        Invocation.getter(#fontSize),
        returnValue: 0.0,
      ) as double);

  @override
  set fontSize(double? _fontSize) => super.noSuchMethod(
        Invocation.setter(
          #fontSize,
          _fontSize,
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<Object?> get props => (super.noSuchMethod(
        Invocation.getter(#props),
        returnValue: <Object?>[],
      ) as List<Object?>);

  @override
  bool get stringify => (super.noSuchMethod(
        Invocation.getter(#stringify),
        returnValue: false,
      ) as bool);

  @override
  _i11.Paint get paint => (super.noSuchMethod(
        Invocation.getter(#paint),
        returnValue: _i18.dummyValue<_i11.Paint>(
          this,
          Invocation.getter(#paint),
        ),
      ) as _i11.Paint);

  @override
  void call(_i11.Canvas? canvas) => super.noSuchMethod(
        Invocation.method(
          #call,
          [canvas],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}

/// A class which mocks [BoundingBox].
///
/// See the documentation for Mockito's code generation for more information.
class MockBoundingBox extends _i1.Mock implements _i20.BoundingBox {
  MockBoundingBox() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Offset get topLeft => (super.noSuchMethod(
        Invocation.getter(#topLeft),
        returnValue: _FakeOffset_12(
          this,
          Invocation.getter(#topLeft),
        ),
      ) as _i11.Offset);

  @override
  set topLeft(_i11.Offset? _topLeft) => super.noSuchMethod(
        Invocation.setter(
          #topLeft,
          _topLeft,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i11.Offset get topRight => (super.noSuchMethod(
        Invocation.getter(#topRight),
        returnValue: _FakeOffset_12(
          this,
          Invocation.getter(#topRight),
        ),
      ) as _i11.Offset);

  @override
  set topRight(_i11.Offset? _topRight) => super.noSuchMethod(
        Invocation.setter(
          #topRight,
          _topRight,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i11.Offset get bottomLeft => (super.noSuchMethod(
        Invocation.getter(#bottomLeft),
        returnValue: _FakeOffset_12(
          this,
          Invocation.getter(#bottomLeft),
        ),
      ) as _i11.Offset);

  @override
  set bottomLeft(_i11.Offset? _bottomLeft) => super.noSuchMethod(
        Invocation.setter(
          #bottomLeft,
          _bottomLeft,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i11.Offset get bottomRight => (super.noSuchMethod(
        Invocation.getter(#bottomRight),
        returnValue: _FakeOffset_12(
          this,
          Invocation.getter(#bottomRight),
        ),
      ) as _i11.Offset);

  @override
  set bottomRight(_i11.Offset? _bottomRight) => super.noSuchMethod(
        Invocation.setter(
          #bottomRight,
          _bottomRight,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i11.Offset get lastPoint => (super.noSuchMethod(
        Invocation.getter(#lastPoint),
        returnValue: _FakeOffset_12(
          this,
          Invocation.getter(#lastPoint),
        ),
      ) as _i11.Offset);

  @override
  set lastPoint(_i11.Offset? _lastPoint) => super.noSuchMethod(
        Invocation.setter(
          #lastPoint,
          _lastPoint,
        ),
        returnValueForMissingStub: null,
      );

  @override
  double get anchorRadius => (super.noSuchMethod(
        Invocation.getter(#anchorRadius),
        returnValue: 0.0,
      ) as double);

  @override
  double get rotationArcOffset => (super.noSuchMethod(
        Invocation.getter(#rotationArcOffset),
        returnValue: 0.0,
      ) as double);

  @override
  double get padding => (super.noSuchMethod(
        Invocation.getter(#padding),
        returnValue: 0.0,
      ) as double);

  @override
  _i21.BoundingBoxCorner get activeCorner => (super.noSuchMethod(
        Invocation.getter(#activeCorner),
        returnValue: _i21.BoundingBoxCorner.none,
      ) as _i21.BoundingBoxCorner);

  @override
  set activeCorner(_i21.BoundingBoxCorner? _activeCorner) => super.noSuchMethod(
        Invocation.setter(
          #activeCorner,
          _activeCorner,
        ),
        returnValueForMissingStub: null,
      );

  @override
  double get edgeSensitivity => (super.noSuchMethod(
        Invocation.getter(#edgeSensitivity),
        returnValue: 0.0,
      ) as double);

  @override
  set edgeSensitivity(double? _edgeSensitivity) => super.noSuchMethod(
        Invocation.setter(
          #edgeSensitivity,
          _edgeSensitivity,
        ),
        returnValueForMissingStub: null,
      );

  @override
  double get rotationArcHandleRadius => (super.noSuchMethod(
        Invocation.getter(#rotationArcHandleRadius),
        returnValue: 0.0,
      ) as double);

  @override
  _i11.Offset get center => (super.noSuchMethod(
        Invocation.getter(#center),
        returnValue: _FakeOffset_12(
          this,
          Invocation.getter(#center),
        ),
      ) as _i11.Offset);

  @override
  double get distanceToEdgeFromCenter => (super.noSuchMethod(
        Invocation.getter(#distanceToEdgeFromCenter),
        returnValue: 0.0,
      ) as double);

  @override
  _i11.Offset get topEdgeCenter => (super.noSuchMethod(
        Invocation.getter(#topEdgeCenter),
        returnValue: _FakeOffset_12(
          this,
          Invocation.getter(#topEdgeCenter),
        ),
      ) as _i11.Offset);

  @override
  double get averageX => (super.noSuchMethod(
        Invocation.getter(#averageX),
        returnValue: 0.0,
      ) as double);

  @override
  double get averageY => (super.noSuchMethod(
        Invocation.getter(#averageY),
        returnValue: 0.0,
      ) as double);

  @override
  double get topLeftBottomRightDiagonal => (super.noSuchMethod(
        Invocation.getter(#topLeftBottomRightDiagonal),
        returnValue: 0.0,
      ) as double);

  @override
  double get topRightBottomLeftDiagonal => (super.noSuchMethod(
        Invocation.getter(#topRightBottomLeftDiagonal),
        returnValue: 0.0,
      ) as double);

  @override
  double get topLeftDirection => (super.noSuchMethod(
        Invocation.getter(#topLeftDirection),
        returnValue: 0.0,
      ) as double);

  @override
  double get topRightDirection => (super.noSuchMethod(
        Invocation.getter(#topRightDirection),
        returnValue: 0.0,
      ) as double);

  @override
  double get bottomLeftDirection => (super.noSuchMethod(
        Invocation.getter(#bottomLeftDirection),
        returnValue: 0.0,
      ) as double);

  @override
  double get bottomRightDirection => (super.noSuchMethod(
        Invocation.getter(#bottomRightDirection),
        returnValue: 0.0,
      ) as double);

  @override
  double get outerRadius => (super.noSuchMethod(
        Invocation.getter(#outerRadius),
        returnValue: 0.0,
      ) as double);

  @override
  double get innerRadius => (super.noSuchMethod(
        Invocation.getter(#innerRadius),
        returnValue: 0.0,
      ) as double);

  @override
  _i11.Offset get topLeftRotationArcCenter => (super.noSuchMethod(
        Invocation.getter(#topLeftRotationArcCenter),
        returnValue: _FakeOffset_12(
          this,
          Invocation.getter(#topLeftRotationArcCenter),
        ),
      ) as _i11.Offset);

  @override
  _i11.Offset get topRightRotationArcCenter => (super.noSuchMethod(
        Invocation.getter(#topRightRotationArcCenter),
        returnValue: _FakeOffset_12(
          this,
          Invocation.getter(#topRightRotationArcCenter),
        ),
      ) as _i11.Offset);

  @override
  _i11.Offset get bottomLeftRotationArcCenter => (super.noSuchMethod(
        Invocation.getter(#bottomLeftRotationArcCenter),
        returnValue: _FakeOffset_12(
          this,
          Invocation.getter(#bottomLeftRotationArcCenter),
        ),
      ) as _i11.Offset);

  @override
  _i11.Offset get bottomRightRotationArcCenter => (super.noSuchMethod(
        Invocation.getter(#bottomRightRotationArcCenter),
        returnValue: _FakeOffset_12(
          this,
          Invocation.getter(#bottomRightRotationArcCenter),
        ),
      ) as _i11.Offset);

  @override
  double get activeCornerDirection => (super.noSuchMethod(
        Invocation.getter(#activeCornerDirection),
        returnValue: 0.0,
      ) as double);

  @override
  void setActiveCorner(_i11.Offset? point) => super.noSuchMethod(
        Invocation.method(
          #setActiveCorner,
          [point],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void scale(_i11.Offset? point) => super.noSuchMethod(
        Invocation.method(
          #scale,
          [point],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawBoundingBox(_i11.Canvas? canvas) => super.noSuchMethod(
        Invocation.method(
          #drawBoundingBox,
          [canvas],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resetActiveCorner() => super.noSuchMethod(
        Invocation.method(
          #resetActiveCorner,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void update(_i11.Offset? point) => super.noSuchMethod(
        Invocation.method(
          #update,
          [point],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateCorners(
    _i11.Offset? topLeft,
    _i11.Offset? topRight,
    _i11.Offset? bottomLeft,
    _i11.Offset? bottomRight, {
    _i11.Offset? offset = _i11.Offset.zero,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #updateCorners,
          [
            topLeft,
            topRight,
            bottomLeft,
            bottomRight,
          ],
          {#offset: offset},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void transform(_i11.Offset? point) => super.noSuchMethod(
        Invocation.method(
          #transform,
          [point],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void rotate(_i11.Offset? point) => super.noSuchMethod(
        Invocation.method(
          #rotate,
          [point],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void moveCenter(_i11.Offset? point) => super.noSuchMethod(
        Invocation.method(
          #moveCenter,
          [point],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i11.Offset getPaddedOffset(
    _i11.Offset? point, {
    double? padding = 0.0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPaddedOffset,
          [point],
          {#padding: padding},
        ),
        returnValue: _FakeOffset_12(
          this,
          Invocation.method(
            #getPaddedOffset,
            [point],
            {#padding: padding},
          ),
        ),
      ) as _i11.Offset);

  @override
  _i11.Offset getPaddedTopLeft({double? padding = 0.0}) => (super.noSuchMethod(
        Invocation.method(
          #getPaddedTopLeft,
          [],
          {#padding: padding},
        ),
        returnValue: _FakeOffset_12(
          this,
          Invocation.method(
            #getPaddedTopLeft,
            [],
            {#padding: padding},
          ),
        ),
      ) as _i11.Offset);

  @override
  _i11.Offset getPaddedTopRight({double? padding = 0.0}) => (super.noSuchMethod(
        Invocation.method(
          #getPaddedTopRight,
          [],
          {#padding: padding},
        ),
        returnValue: _FakeOffset_12(
          this,
          Invocation.method(
            #getPaddedTopRight,
            [],
            {#padding: padding},
          ),
        ),
      ) as _i11.Offset);

  @override
  _i11.Offset getPaddedBottomLeft({double? padding = 0.0}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPaddedBottomLeft,
          [],
          {#padding: padding},
        ),
        returnValue: _FakeOffset_12(
          this,
          Invocation.method(
            #getPaddedBottomLeft,
            [],
            {#padding: padding},
          ),
        ),
      ) as _i11.Offset);

  @override
  _i11.Offset getPaddedBottomRight({double? padding = 0.0}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPaddedBottomRight,
          [],
          {#padding: padding},
        ),
        returnValue: _FakeOffset_12(
          this,
          Invocation.method(
            #getPaddedBottomRight,
            [],
            {#padding: padding},
          ),
        ),
      ) as _i11.Offset);

  @override
  _i11.Path getPath({double? padding = 0.0}) => (super.noSuchMethod(
        Invocation.method(
          #getPath,
          [],
          {#padding: padding},
        ),
        returnValue: _FakePath_14(
          this,
          Invocation.method(
            #getPath,
            [],
            {#padding: padding},
          ),
        ),
      ) as _i11.Path);
}
