// Mocks generated by Mockito 5.4.4 from annotations
// in paintroid/test/unit/tools/text_tool_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i26;
import 'dart:typed_data' as _i24;
import 'dart:ui' as _i16;

import 'package:flutter/material.dart' as _i17;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i25;
import 'package:paintroid/core/commands/command_factory/command_factory.dart'
    as _i22;
import 'package:paintroid/core/commands/command_implementation/command.dart'
    as _i2;
import 'package:paintroid/core/commands/command_implementation/graphic/clipboard_command.dart'
    as _i8;
import 'package:paintroid/core/commands/command_implementation/graphic/color_changed_command.dart'
    as _i14;
import 'package:paintroid/core/commands/command_implementation/graphic/delete_region_command.dart'
    as _i13;
import 'package:paintroid/core/commands/command_implementation/graphic/graphic_command.dart'
    as _i20;
import 'package:paintroid/core/commands/command_implementation/graphic/line_command.dart'
    as _i5;
import 'package:paintroid/core/commands/command_implementation/graphic/path_command.dart'
    as _i4;
import 'package:paintroid/core/commands/command_implementation/graphic/shape/ellipse_shape_command.dart'
    as _i7;
import 'package:paintroid/core/commands/command_implementation/graphic/shape/heart_shape_command.dart'
    as _i11;
import 'package:paintroid/core/commands/command_implementation/graphic/shape/square_shape_command.dart'
    as _i6;
import 'package:paintroid/core/commands/command_implementation/graphic/shape/star_shape_command.dart'
    as _i10;
import 'package:paintroid/core/commands/command_implementation/graphic/spray_command.dart'
    as _i12;
import 'package:paintroid/core/commands/command_implementation/graphic/text_command.dart'
    as _i9;
import 'package:paintroid/core/commands/command_manager/command_manager.dart'
    as _i19;
import 'package:paintroid/core/commands/graphic_factory/graphic_factory.dart'
    as _i27;
import 'package:paintroid/core/commands/path_with_action_history.dart' as _i18;
import 'package:paintroid/core/enums/bounding_box_action.dart' as _i29;
import 'package:paintroid/core/enums/bounding_box_resize_action.dart' as _i30;
import 'package:paintroid/core/enums/shape_style.dart' as _i23;
import 'package:paintroid/core/tools/bounding_box.dart' as _i28;
import 'package:paintroid/core/tools/line_tool/vertex_stack.dart' as _i21;
import 'package:paintroid/core/tools/tool_data.dart' as _i3;
import 'package:riverpod/src/internals.dart' as _i15;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCommand_0 extends _i1.SmartFake implements _i2.Command {
  _FakeCommand_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeToolData_1 extends _i1.SmartFake implements _i3.ToolData {
  _FakeToolData_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePathCommand_2 extends _i1.SmartFake implements _i4.PathCommand {
  _FakePathCommand_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLineCommand_3 extends _i1.SmartFake implements _i5.LineCommand {
  _FakeLineCommand_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSquareShapeCommand_4 extends _i1.SmartFake
    implements _i6.SquareShapeCommand {
  _FakeSquareShapeCommand_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEllipseShapeCommand_5 extends _i1.SmartFake
    implements _i7.EllipseShapeCommand {
  _FakeEllipseShapeCommand_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClipboardCommand_6 extends _i1.SmartFake
    implements _i8.ClipboardCommand {
  _FakeClipboardCommand_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTextCommand_7 extends _i1.SmartFake implements _i9.TextCommand {
  _FakeTextCommand_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStarShapeCommand_8 extends _i1.SmartFake
    implements _i10.StarShapeCommand {
  _FakeStarShapeCommand_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHeartShapeCommand_9 extends _i1.SmartFake
    implements _i11.HeartShapeCommand {
  _FakeHeartShapeCommand_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSprayCommand_10 extends _i1.SmartFake implements _i12.SprayCommand {
  _FakeSprayCommand_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeleteRegionCommand_11 extends _i1.SmartFake
    implements _i13.DeleteRegionCommand {
  _FakeDeleteRegionCommand_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeColorChangedCommand_12 extends _i1.SmartFake
    implements _i14.ColorChangedCommand {
  _FakeColorChangedCommand_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProviderContainer_13 extends _i1.SmartFake
    implements _i15.ProviderContainer {
  _FakeProviderContainer_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeKeepAliveLink_14 extends _i1.SmartFake
    implements _i15.KeepAliveLink {
  _FakeKeepAliveLink_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProviderSubscription_15<State1> extends _i1.SmartFake
    implements _i15.ProviderSubscription<State1> {
  _FakeProviderSubscription_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRect_16 extends _i1.SmartFake implements _i16.Rect {
  _FakeRect_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOffset_17 extends _i1.SmartFake implements _i16.Offset {
  _FakeOffset_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTextStyle_18 extends _i1.SmartFake implements _i17.TextStyle {
  _FakeTextStyle_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString(
          {_i17.DiagnosticLevel? minLevel = _i17.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakePathWithActionHistory_19 extends _i1.SmartFake
    implements _i18.PathWithActionHistory {
  _FakePathWithActionHistory_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePictureRecorder_20 extends _i1.SmartFake
    implements _i16.PictureRecorder {
  _FakePictureRecorder_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCanvas_21 extends _i1.SmartFake implements _i16.Canvas {
  _FakeCanvas_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CommandManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommandManager extends _i1.Mock implements _i19.CommandManager {
  MockCommandManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.Command> get redoStack => (super.noSuchMethod(
        Invocation.getter(#redoStack),
        returnValue: <_i2.Command>[],
      ) as List<_i2.Command>);

  @override
  List<_i2.Command> get undoStack => (super.noSuchMethod(
        Invocation.getter(#undoStack),
        returnValue: <_i2.Command>[],
      ) as List<_i2.Command>);

  @override
  void addGraphicCommand(_i20.GraphicCommand? command) => super.noSuchMethod(
        Invocation.method(
          #addGraphicCommand,
          [command],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setUndoStack(List<_i2.Command>? commands) => super.noSuchMethod(
        Invocation.method(
          #setUndoStack,
          [commands],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void executeLastCommand(_i16.Canvas? canvas) => super.noSuchMethod(
        Invocation.method(
          #executeLastCommand,
          [canvas],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void executeAllCommands(_i16.Canvas? canvas) => super.noSuchMethod(
        Invocation.method(
          #executeAllCommands,
          [canvas],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void discardLastCommand() => super.noSuchMethod(
        Invocation.method(
          #discardLastCommand,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearUndoStack({Iterable<_i2.Command>? newCommands}) =>
      super.noSuchMethod(
        Invocation.method(
          #clearUndoStack,
          [],
          {#newCommands: newCommands},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearRedoStack() => super.noSuchMethod(
        Invocation.method(
          #clearRedoStack,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawLineToolGhostPaths(
    _i16.Canvas? canvas,
    _i5.LineCommand? ingoingGhostPathCommand,
    _i5.LineCommand? outgoingGhostPathCommand,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #drawLineToolGhostPaths,
          [
            canvas,
            ingoingGhostPathCommand,
            outgoingGhostPathCommand,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawLineToolVertices(
    _i16.Canvas? canvas,
    _i21.VertexStack? vertexStack,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #drawLineToolVertices,
          [
            canvas,
            vertexStack,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Command redo() => (super.noSuchMethod(
        Invocation.method(
          #redo,
          [],
        ),
        returnValue: _FakeCommand_0(
          this,
          Invocation.method(
            #redo,
            [],
          ),
        ),
      ) as _i2.Command);

  @override
  void undo() => super.noSuchMethod(
        Invocation.method(
          #undo,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.ToolData getNextTool(_i19.ActionType? actionType) => (super.noSuchMethod(
        Invocation.method(
          #getNextTool,
          [actionType],
        ),
        returnValue: _FakeToolData_1(
          this,
          Invocation.method(
            #getNextTool,
            [actionType],
          ),
        ),
      ) as _i3.ToolData);

  @override
  List<_i5.LineCommand> getTopLineCommandSequence() => (super.noSuchMethod(
        Invocation.method(
          #getTopLineCommandSequence,
          [],
        ),
        returnValue: <_i5.LineCommand>[],
      ) as List<_i5.LineCommand>);
}

/// A class which mocks [CommandFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommandFactory extends _i1.Mock implements _i22.CommandFactory {
  MockCommandFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.PathCommand createPathCommand(
    _i18.PathWithActionHistory? path,
    _i16.Paint? paint, {
    bool? isCursor = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPathCommand,
          [
            path,
            paint,
          ],
          {#isCursor: isCursor},
        ),
        returnValue: _FakePathCommand_2(
          this,
          Invocation.method(
            #createPathCommand,
            [
              path,
              paint,
            ],
            {#isCursor: isCursor},
          ),
        ),
      ) as _i4.PathCommand);

  @override
  _i5.LineCommand createLineCommand(
    _i18.PathWithActionHistory? path,
    _i16.Paint? paint,
    _i16.Offset? startPoint,
    _i16.Offset? endPoint,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createLineCommand,
          [
            path,
            paint,
            startPoint,
            endPoint,
          ],
        ),
        returnValue: _FakeLineCommand_3(
          this,
          Invocation.method(
            #createLineCommand,
            [
              path,
              paint,
              startPoint,
              endPoint,
            ],
          ),
        ),
      ) as _i5.LineCommand);

  @override
  _i6.SquareShapeCommand createSquareShapeCommand(
    _i16.Paint? paint,
    _i16.Offset? topLeft,
    _i16.Offset? topRight,
    _i16.Offset? bottomLeft,
    _i16.Offset? bottomRight,
    _i23.ShapeStyle? style,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSquareShapeCommand,
          [
            paint,
            topLeft,
            topRight,
            bottomLeft,
            bottomRight,
            style,
          ],
        ),
        returnValue: _FakeSquareShapeCommand_4(
          this,
          Invocation.method(
            #createSquareShapeCommand,
            [
              paint,
              topLeft,
              topRight,
              bottomLeft,
              bottomRight,
              style,
            ],
          ),
        ),
      ) as _i6.SquareShapeCommand);

  @override
  _i7.EllipseShapeCommand createEllipseShapeCommand(
    _i16.Paint? paint,
    double? radiusX,
    double? radiusY,
    _i16.Offset? center,
    _i23.ShapeStyle? style,
    double? angle,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createEllipseShapeCommand,
          [
            paint,
            radiusX,
            radiusY,
            center,
            style,
            angle,
          ],
        ),
        returnValue: _FakeEllipseShapeCommand_5(
          this,
          Invocation.method(
            #createEllipseShapeCommand,
            [
              paint,
              radiusX,
              radiusY,
              center,
              style,
              angle,
            ],
          ),
        ),
      ) as _i7.EllipseShapeCommand);

  @override
  _i8.ClipboardCommand createClipboardCommand(
    _i16.Paint? paint,
    _i24.Uint8List? imageData,
    _i16.Offset? offset,
    double? scale,
    double? rotation,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createClipboardCommand,
          [
            paint,
            imageData,
            offset,
            scale,
            rotation,
          ],
        ),
        returnValue: _FakeClipboardCommand_6(
          this,
          Invocation.method(
            #createClipboardCommand,
            [
              paint,
              imageData,
              offset,
              scale,
              rotation,
            ],
          ),
        ),
      ) as _i8.ClipboardCommand);

  @override
  _i9.TextCommand createTextCommand(
    _i16.Offset? point,
    String? text,
    _i17.TextStyle? style,
    double? fontSize,
    _i16.Paint? paint,
    double? rotationAngle, {
    double? scaleX = 1.0,
    double? scaleY = 1.0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTextCommand,
          [
            point,
            text,
            style,
            fontSize,
            paint,
            rotationAngle,
          ],
          {
            #scaleX: scaleX,
            #scaleY: scaleY,
          },
        ),
        returnValue: _FakeTextCommand_7(
          this,
          Invocation.method(
            #createTextCommand,
            [
              point,
              text,
              style,
              fontSize,
              paint,
              rotationAngle,
            ],
            {
              #scaleX: scaleX,
              #scaleY: scaleY,
            },
          ),
        ),
      ) as _i9.TextCommand);

  @override
  _i10.StarShapeCommand createStarShapeCommand(
    _i16.Paint? paint,
    int? numPoints,
    double? angle,
    _i16.Offset? center,
    _i23.ShapeStyle? style,
    double? radiusX,
    double? radiusY,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createStarShapeCommand,
          [
            paint,
            numPoints,
            angle,
            center,
            style,
            radiusX,
            radiusY,
          ],
        ),
        returnValue: _FakeStarShapeCommand_8(
          this,
          Invocation.method(
            #createStarShapeCommand,
            [
              paint,
              numPoints,
              angle,
              center,
              style,
              radiusX,
              radiusY,
            ],
          ),
        ),
      ) as _i10.StarShapeCommand);

  @override
  _i11.HeartShapeCommand createHeartShapeCommand(
    _i16.Paint? paint,
    double? width,
    double? height,
    double? angle,
    _i16.Offset? center,
    _i23.ShapeStyle? style,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createHeartShapeCommand,
          [
            paint,
            width,
            height,
            angle,
            center,
            style,
          ],
        ),
        returnValue: _FakeHeartShapeCommand_9(
          this,
          Invocation.method(
            #createHeartShapeCommand,
            [
              paint,
              width,
              height,
              angle,
              center,
              style,
            ],
          ),
        ),
      ) as _i11.HeartShapeCommand);

  @override
  _i12.SprayCommand createSprayCommand(
    List<_i16.Offset>? points,
    _i16.Paint? paint,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSprayCommand,
          [
            points,
            paint,
          ],
        ),
        returnValue: _FakeSprayCommand_10(
          this,
          Invocation.method(
            #createSprayCommand,
            [
              points,
              paint,
            ],
          ),
        ),
      ) as _i12.SprayCommand);

  @override
  _i13.DeleteRegionCommand createDeleteRegionCommand(_i16.Rect? region) =>
      (super.noSuchMethod(
        Invocation.method(
          #createDeleteRegionCommand,
          [region],
        ),
        returnValue: _FakeDeleteRegionCommand_11(
          this,
          Invocation.method(
            #createDeleteRegionCommand,
            [region],
          ),
        ),
      ) as _i13.DeleteRegionCommand);

  @override
  _i14.ColorChangedCommand createColorChangedCommand(
    _i16.Color? oldColor,
    _i16.Color? newColor,
    _i16.Paint? paint,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createColorChangedCommand,
          [
            oldColor,
            newColor,
            paint,
          ],
        ),
        returnValue: _FakeColorChangedCommand_12(
          this,
          Invocation.method(
            #createColorChangedCommand,
            [
              oldColor,
              newColor,
              paint,
            ],
          ),
        ),
      ) as _i14.ColorChangedCommand);
}

/// A class which mocks [Ref].
///
/// See the documentation for Mockito's code generation for more information.
class MockRef<State extends Object?> extends _i1.Mock
    implements _i15.Ref<State> {
  MockRef() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i15.ProviderContainer get container => (super.noSuchMethod(
        Invocation.getter(#container),
        returnValue: _FakeProviderContainer_13(
          this,
          Invocation.getter(#container),
        ),
      ) as _i15.ProviderContainer);

  @override
  T refresh<T>(_i15.Refreshable<T>? provider) => (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [provider],
        ),
        returnValue: _i25.dummyValue<T>(
          this,
          Invocation.method(
            #refresh,
            [provider],
          ),
        ),
      ) as T);

  @override
  void invalidate(_i15.ProviderOrFamily? provider) => super.noSuchMethod(
        Invocation.method(
          #invalidate,
          [provider],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void listenSelf(
    void Function(
      State?,
      State,
    )? listener, {
    void Function(
      Object,
      StackTrace,
    )? onError,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #listenSelf,
          [listener],
          {#onError: onError},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void invalidateSelf() => super.noSuchMethod(
        Invocation.method(
          #invalidateSelf,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onAddListener(void Function()? cb) => super.noSuchMethod(
        Invocation.method(
          #onAddListener,
          [cb],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onRemoveListener(void Function()? cb) => super.noSuchMethod(
        Invocation.method(
          #onRemoveListener,
          [cb],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onResume(void Function()? cb) => super.noSuchMethod(
        Invocation.method(
          #onResume,
          [cb],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onCancel(void Function()? cb) => super.noSuchMethod(
        Invocation.method(
          #onCancel,
          [cb],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDispose(void Function()? cb) => super.noSuchMethod(
        Invocation.method(
          #onDispose,
          [cb],
        ),
        returnValueForMissingStub: null,
      );

  @override
  T read<T>(_i15.ProviderListenable<T>? provider) => (super.noSuchMethod(
        Invocation.method(
          #read,
          [provider],
        ),
        returnValue: _i25.dummyValue<T>(
          this,
          Invocation.method(
            #read,
            [provider],
          ),
        ),
      ) as T);

  @override
  bool exists(_i15.ProviderBase<Object?>? provider) => (super.noSuchMethod(
        Invocation.method(
          #exists,
          [provider],
        ),
        returnValue: false,
      ) as bool);

  @override
  T watch<T>(_i15.ProviderListenable<T>? provider) => (super.noSuchMethod(
        Invocation.method(
          #watch,
          [provider],
        ),
        returnValue: _i25.dummyValue<T>(
          this,
          Invocation.method(
            #watch,
            [provider],
          ),
        ),
      ) as T);

  @override
  _i15.KeepAliveLink keepAlive() => (super.noSuchMethod(
        Invocation.method(
          #keepAlive,
          [],
        ),
        returnValue: _FakeKeepAliveLink_14(
          this,
          Invocation.method(
            #keepAlive,
            [],
          ),
        ),
      ) as _i15.KeepAliveLink);

  @override
  _i15.ProviderSubscription<T> listen<T>(
    _i15.ProviderListenable<T>? provider,
    void Function(
      T?,
      T,
    )? listener, {
    void Function(
      Object,
      StackTrace,
    )? onError,
    bool? fireImmediately,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listen,
          [
            provider,
            listener,
          ],
          {
            #onError: onError,
            #fireImmediately: fireImmediately,
          },
        ),
        returnValue: _FakeProviderSubscription_15<T>(
          this,
          Invocation.method(
            #listen,
            [
              provider,
              listener,
            ],
            {
              #onError: onError,
              #fireImmediately: fireImmediately,
            },
          ),
        ),
      ) as _i15.ProviderSubscription<T>);
}

/// A class which mocks [Canvas].
///
/// See the documentation for Mockito's code generation for more information.
class MockCanvas extends _i1.Mock implements _i16.Canvas {
  MockCanvas() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void save() => super.noSuchMethod(
        Invocation.method(
          #save,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void saveLayer(
    _i16.Rect? bounds,
    _i16.Paint? paint,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #saveLayer,
          [
            bounds,
            paint,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void restore() => super.noSuchMethod(
        Invocation.method(
          #restore,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void restoreToCount(int? count) => super.noSuchMethod(
        Invocation.method(
          #restoreToCount,
          [count],
        ),
        returnValueForMissingStub: null,
      );

  @override
  int getSaveCount() => (super.noSuchMethod(
        Invocation.method(
          #getSaveCount,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  void translate(
    double? dx,
    double? dy,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #translate,
          [
            dx,
            dy,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void scale(
    double? sx, [
    double? sy,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #scale,
          [
            sx,
            sy,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void rotate(double? radians) => super.noSuchMethod(
        Invocation.method(
          #rotate,
          [radians],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void skew(
    double? sx,
    double? sy,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #skew,
          [
            sx,
            sy,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void transform(_i24.Float64List? matrix4) => super.noSuchMethod(
        Invocation.method(
          #transform,
          [matrix4],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i24.Float64List getTransform() => (super.noSuchMethod(
        Invocation.method(
          #getTransform,
          [],
        ),
        returnValue: _i24.Float64List(0),
      ) as _i24.Float64List);

  @override
  void clipRect(
    _i16.Rect? rect, {
    _i16.ClipOp? clipOp = _i16.ClipOp.intersect,
    bool? doAntiAlias = true,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #clipRect,
          [rect],
          {
            #clipOp: clipOp,
            #doAntiAlias: doAntiAlias,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clipRRect(
    _i16.RRect? rrect, {
    bool? doAntiAlias = true,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #clipRRect,
          [rrect],
          {#doAntiAlias: doAntiAlias},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clipRSuperellipse(
    _i16.RSuperellipse? rsuperellipse, {
    bool? doAntiAlias = true,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #clipRSuperellipse,
          [rsuperellipse],
          {#doAntiAlias: doAntiAlias},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clipPath(
    _i16.Path? path, {
    bool? doAntiAlias = true,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #clipPath,
          [path],
          {#doAntiAlias: doAntiAlias},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i16.Rect getLocalClipBounds() => (super.noSuchMethod(
        Invocation.method(
          #getLocalClipBounds,
          [],
        ),
        returnValue: _FakeRect_16(
          this,
          Invocation.method(
            #getLocalClipBounds,
            [],
          ),
        ),
      ) as _i16.Rect);

  @override
  _i16.Rect getDestinationClipBounds() => (super.noSuchMethod(
        Invocation.method(
          #getDestinationClipBounds,
          [],
        ),
        returnValue: _FakeRect_16(
          this,
          Invocation.method(
            #getDestinationClipBounds,
            [],
          ),
        ),
      ) as _i16.Rect);

  @override
  void drawColor(
    _i16.Color? color,
    _i16.BlendMode? blendMode,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #drawColor,
          [
            color,
            blendMode,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawLine(
    _i16.Offset? p1,
    _i16.Offset? p2,
    _i16.Paint? paint,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #drawLine,
          [
            p1,
            p2,
            paint,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawPaint(_i16.Paint? paint) => super.noSuchMethod(
        Invocation.method(
          #drawPaint,
          [paint],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawRect(
    _i16.Rect? rect,
    _i16.Paint? paint,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #drawRect,
          [
            rect,
            paint,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawRRect(
    _i16.RRect? rrect,
    _i16.Paint? paint,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #drawRRect,
          [
            rrect,
            paint,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawDRRect(
    _i16.RRect? outer,
    _i16.RRect? inner,
    _i16.Paint? paint,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #drawDRRect,
          [
            outer,
            inner,
            paint,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawRSuperellipse(
    _i16.RSuperellipse? rsuperellipse,
    _i16.Paint? paint,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #drawRSuperellipse,
          [
            rsuperellipse,
            paint,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawOval(
    _i16.Rect? rect,
    _i16.Paint? paint,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #drawOval,
          [
            rect,
            paint,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawCircle(
    _i16.Offset? c,
    double? radius,
    _i16.Paint? paint,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #drawCircle,
          [
            c,
            radius,
            paint,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawArc(
    _i16.Rect? rect,
    double? startAngle,
    double? sweepAngle,
    bool? useCenter,
    _i16.Paint? paint,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #drawArc,
          [
            rect,
            startAngle,
            sweepAngle,
            useCenter,
            paint,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawPath(
    _i16.Path? path,
    _i16.Paint? paint,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #drawPath,
          [
            path,
            paint,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawImage(
    _i16.Image? image,
    _i16.Offset? offset,
    _i16.Paint? paint,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #drawImage,
          [
            image,
            offset,
            paint,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawImageRect(
    _i16.Image? image,
    _i16.Rect? src,
    _i16.Rect? dst,
    _i16.Paint? paint,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #drawImageRect,
          [
            image,
            src,
            dst,
            paint,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawImageNine(
    _i16.Image? image,
    _i16.Rect? center,
    _i16.Rect? dst,
    _i16.Paint? paint,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #drawImageNine,
          [
            image,
            center,
            dst,
            paint,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawPicture(_i16.Picture? picture) => super.noSuchMethod(
        Invocation.method(
          #drawPicture,
          [picture],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawParagraph(
    _i16.Paragraph? paragraph,
    _i16.Offset? offset,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #drawParagraph,
          [
            paragraph,
            offset,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawPoints(
    _i16.PointMode? pointMode,
    List<_i16.Offset>? points,
    _i16.Paint? paint,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #drawPoints,
          [
            pointMode,
            points,
            paint,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawRawPoints(
    _i16.PointMode? pointMode,
    _i24.Float32List? points,
    _i16.Paint? paint,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #drawRawPoints,
          [
            pointMode,
            points,
            paint,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawVertices(
    _i16.Vertices? vertices,
    _i16.BlendMode? blendMode,
    _i16.Paint? paint,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #drawVertices,
          [
            vertices,
            blendMode,
            paint,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawAtlas(
    _i16.Image? atlas,
    List<_i16.RSTransform>? transforms,
    List<_i16.Rect>? rects,
    List<_i16.Color>? colors,
    _i16.BlendMode? blendMode,
    _i16.Rect? cullRect,
    _i16.Paint? paint,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #drawAtlas,
          [
            atlas,
            transforms,
            rects,
            colors,
            blendMode,
            cullRect,
            paint,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawRawAtlas(
    _i16.Image? atlas,
    _i24.Float32List? rstTransforms,
    _i24.Float32List? rects,
    _i24.Int32List? colors,
    _i16.BlendMode? blendMode,
    _i16.Rect? cullRect,
    _i16.Paint? paint,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #drawRawAtlas,
          [
            atlas,
            rstTransforms,
            rects,
            colors,
            blendMode,
            cullRect,
            paint,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawShadow(
    _i16.Path? path,
    _i16.Color? color,
    double? elevation,
    bool? transparentOccluder,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #drawShadow,
          [
            path,
            color,
            elevation,
            transparentOccluder,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [TextCommand].
///
/// See the documentation for Mockito's code generation for more information.
class MockTextCommand extends _i1.Mock implements _i9.TextCommand {
  MockTextCommand() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.Offset get point => (super.noSuchMethod(
        Invocation.getter(#point),
        returnValue: _FakeOffset_17(
          this,
          Invocation.getter(#point),
        ),
      ) as _i16.Offset);

  @override
  set point(_i16.Offset? _point) => super.noSuchMethod(
        Invocation.setter(
          #point,
          _point,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i17.TextStyle get style => (super.noSuchMethod(
        Invocation.getter(#style),
        returnValue: _FakeTextStyle_18(
          this,
          Invocation.getter(#style),
        ),
      ) as _i17.TextStyle);

  @override
  String get text => (super.noSuchMethod(
        Invocation.getter(#text),
        returnValue: _i25.dummyValue<String>(
          this,
          Invocation.getter(#text),
        ),
      ) as String);

  @override
  double get rotationAngle => (super.noSuchMethod(
        Invocation.getter(#rotationAngle),
        returnValue: 0.0,
      ) as double);

  @override
  int get version => (super.noSuchMethod(
        Invocation.getter(#version),
        returnValue: 0,
      ) as int);

  @override
  String get type => (super.noSuchMethod(
        Invocation.getter(#type),
        returnValue: _i25.dummyValue<String>(
          this,
          Invocation.getter(#type),
        ),
      ) as String);

  @override
  double get fontSize => (super.noSuchMethod(
        Invocation.getter(#fontSize),
        returnValue: 0.0,
      ) as double);

  @override
  double get scaleX => (super.noSuchMethod(
        Invocation.getter(#scaleX),
        returnValue: 0.0,
      ) as double);

  @override
  double get scaleY => (super.noSuchMethod(
        Invocation.getter(#scaleY),
        returnValue: 0.0,
      ) as double);

  @override
  List<Object?> get props => (super.noSuchMethod(
        Invocation.getter(#props),
        returnValue: <Object?>[],
      ) as List<Object?>);

  @override
  bool get stringify => (super.noSuchMethod(
        Invocation.getter(#stringify),
        returnValue: false,
      ) as bool);

  @override
  _i16.Paint get paint => (super.noSuchMethod(
        Invocation.getter(#paint),
        returnValue: _i25.dummyValue<_i16.Paint>(
          this,
          Invocation.getter(#paint),
        ),
      ) as _i16.Paint);

  @override
  void call(_i16.Canvas? canvas) => super.noSuchMethod(
        Invocation.method(
          #call,
          [canvas],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i26.Future<void> prepareForRuntime() => (super.noSuchMethod(
        Invocation.method(
          #prepareForRuntime,
          [],
        ),
        returnValue: _i26.Future<void>.value(),
        returnValueForMissingStub: _i26.Future<void>.value(),
      ) as _i26.Future<void>);
}

/// A class which mocks [GraphicFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockGraphicFactory extends _i1.Mock implements _i27.GraphicFactory {
  MockGraphicFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.Paint createPaint() => (super.noSuchMethod(
        Invocation.method(
          #createPaint,
          [],
        ),
        returnValue: _i25.dummyValue<_i16.Paint>(
          this,
          Invocation.method(
            #createPaint,
            [],
          ),
        ),
      ) as _i16.Paint);

  @override
  _i18.PathWithActionHistory createPathWithActionHistory() =>
      (super.noSuchMethod(
        Invocation.method(
          #createPathWithActionHistory,
          [],
        ),
        returnValue: _FakePathWithActionHistory_19(
          this,
          Invocation.method(
            #createPathWithActionHistory,
            [],
          ),
        ),
      ) as _i18.PathWithActionHistory);

  @override
  _i16.PictureRecorder createPictureRecorder() => (super.noSuchMethod(
        Invocation.method(
          #createPictureRecorder,
          [],
        ),
        returnValue: _FakePictureRecorder_20(
          this,
          Invocation.method(
            #createPictureRecorder,
            [],
          ),
        ),
      ) as _i16.PictureRecorder);

  @override
  _i16.Canvas createCanvasWithRecorder(_i16.PictureRecorder? recorder) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCanvasWithRecorder,
          [recorder],
        ),
        returnValue: _FakeCanvas_21(
          this,
          Invocation.method(
            #createCanvasWithRecorder,
            [recorder],
          ),
        ),
      ) as _i16.Canvas);

  @override
  _i16.Paint createWatercolorPaint(
    _i16.Paint? originalPaint,
    double? blurSigma,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createWatercolorPaint,
          [
            originalPaint,
            blurSigma,
          ],
        ),
        returnValue: _i25.dummyValue<_i16.Paint>(
          this,
          Invocation.method(
            #createWatercolorPaint,
            [
              originalPaint,
              blurSigma,
            ],
          ),
        ),
      ) as _i16.Paint);

  @override
  _i16.Paint copyPaint(_i16.Paint? original) => (super.noSuchMethod(
        Invocation.method(
          #copyPaint,
          [original],
        ),
        returnValue: _i25.dummyValue<_i16.Paint>(
          this,
          Invocation.method(
            #copyPaint,
            [original],
          ),
        ),
      ) as _i16.Paint);
}

/// A class which mocks [BoundingBox].
///
/// See the documentation for Mockito's code generation for more information.
class MockBoundingBox extends _i1.Mock implements _i28.BoundingBox {
  MockBoundingBox() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.Offset get center => (super.noSuchMethod(
        Invocation.getter(#center),
        returnValue: _FakeOffset_17(
          this,
          Invocation.getter(#center),
        ),
      ) as _i16.Offset);

  @override
  set center(_i16.Offset? _center) => super.noSuchMethod(
        Invocation.setter(
          #center,
          _center,
        ),
        returnValueForMissingStub: null,
      );

  @override
  double get width => (super.noSuchMethod(
        Invocation.getter(#width),
        returnValue: 0.0,
      ) as double);

  @override
  set width(double? _width) => super.noSuchMethod(
        Invocation.setter(
          #width,
          _width,
        ),
        returnValueForMissingStub: null,
      );

  @override
  double get height => (super.noSuchMethod(
        Invocation.getter(#height),
        returnValue: 0.0,
      ) as double);

  @override
  set height(double? _height) => super.noSuchMethod(
        Invocation.setter(
          #height,
          _height,
        ),
        returnValueForMissingStub: null,
      );

  @override
  double get angle => (super.noSuchMethod(
        Invocation.getter(#angle),
        returnValue: 0.0,
      ) as double);

  @override
  set angle(double? _angle) => super.noSuchMethod(
        Invocation.setter(
          #angle,
          _angle,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i29.BoundingBoxAction get currentAction => (super.noSuchMethod(
        Invocation.getter(#currentAction),
        returnValue: _i29.BoundingBoxAction.none,
      ) as _i29.BoundingBoxAction);

  @override
  set currentAction(_i29.BoundingBoxAction? _currentAction) =>
      super.noSuchMethod(
        Invocation.setter(
          #currentAction,
          _currentAction,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i30.BoundingBoxResizeAction get currentBoundingBoxResizeAction =>
      (super.noSuchMethod(
        Invocation.getter(#currentBoundingBoxResizeAction),
        returnValue: _i30.BoundingBoxResizeAction.none,
      ) as _i30.BoundingBoxResizeAction);

  @override
  set currentBoundingBoxResizeAction(
          _i30.BoundingBoxResizeAction? _currentBoundingBoxResizeAction) =>
      super.noSuchMethod(
        Invocation.setter(
          #currentBoundingBoxResizeAction,
          _currentBoundingBoxResizeAction,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set lastDragGlobalPosition(_i16.Offset? _lastDragGlobalPosition) =>
      super.noSuchMethod(
        Invocation.setter(
          #lastDragGlobalPosition,
          _lastDragGlobalPosition,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set dragStartLocalPosition(_i16.Offset? _dragStartLocalPosition) =>
      super.noSuchMethod(
        Invocation.setter(
          #dragStartLocalPosition,
          _dragStartLocalPosition,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get activeRotationArcIndex => (super.noSuchMethod(
        Invocation.getter(#activeRotationArcIndex),
        returnValue: 0,
      ) as int);

  @override
  set activeRotationArcIndex(int? _activeRotationArcIndex) =>
      super.noSuchMethod(
        Invocation.setter(
          #activeRotationArcIndex,
          _activeRotationArcIndex,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i16.Paint get boxPaint => (super.noSuchMethod(
        Invocation.getter(#boxPaint),
        returnValue: _i25.dummyValue<_i16.Paint>(
          this,
          Invocation.getter(#boxPaint),
        ),
      ) as _i16.Paint);

  @override
  set boxPaint(_i16.Paint? _boxPaint) => super.noSuchMethod(
        Invocation.setter(
          #boxPaint,
          _boxPaint,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i16.Paint get handlePaint => (super.noSuchMethod(
        Invocation.getter(#handlePaint),
        returnValue: _i25.dummyValue<_i16.Paint>(
          this,
          Invocation.getter(#handlePaint),
        ),
      ) as _i16.Paint);

  @override
  set handlePaint(_i16.Paint? _handlePaint) => super.noSuchMethod(
        Invocation.setter(
          #handlePaint,
          _handlePaint,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i16.Paint get rotationHandlePaint => (super.noSuchMethod(
        Invocation.getter(#rotationHandlePaint),
        returnValue: _i25.dummyValue<_i16.Paint>(
          this,
          Invocation.getter(#rotationHandlePaint),
        ),
      ) as _i16.Paint);

  @override
  set rotationHandlePaint(_i16.Paint? _rotationHandlePaint) =>
      super.noSuchMethod(
        Invocation.setter(
          #rotationHandlePaint,
          _rotationHandlePaint,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get isAspectRatioLocked => (super.noSuchMethod(
        Invocation.getter(#isAspectRatioLocked),
        returnValue: false,
      ) as bool);

  @override
  set isAspectRatioLocked(bool? _isAspectRatioLocked) => super.noSuchMethod(
        Invocation.setter(
          #isAspectRatioLocked,
          _isAspectRatioLocked,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i16.Rect get rect => (super.noSuchMethod(
        Invocation.getter(#rect),
        returnValue: _FakeRect_16(
          this,
          Invocation.getter(#rect),
        ),
      ) as _i16.Rect);

  @override
  List<_i16.Offset> getCorners() => (super.noSuchMethod(
        Invocation.method(
          #getCorners,
          [],
        ),
        returnValue: <_i16.Offset>[],
      ) as List<_i16.Offset>);

  @override
  void determineAction(_i16.Offset? globalPoint) => super.noSuchMethod(
        Invocation.method(
          #determineAction,
          [globalPoint],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateDrag(_i16.Offset? globalPoint) => super.noSuchMethod(
        Invocation.method(
          #updateDrag,
          [globalPoint],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void endDrag() => super.noSuchMethod(
        Invocation.method(
          #endDrag,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawGuides(_i16.Canvas? canvas) => super.noSuchMethod(
        Invocation.method(
          #drawGuides,
          [canvas],
        ),
        returnValueForMissingStub: null,
      );
}
