// ignore_for_file: must_be_immutable

import 'package:flutter/material.dart';

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:paintroid/core/commands/command_implementation/graphic/shape/shape_command.dart';
import 'package:paintroid/core/enums/shape_style.dart';
import 'package:paintroid/core/json_serialization/converter/offset_converter.dart';
import 'package:paintroid/core/json_serialization/converter/paint_converter.dart';
import 'package:paintroid/core/json_serialization/versioning/serializer_version.dart';
import 'package:paintroid/core/json_serialization/versioning/version_strategy.dart';
import 'package:paintroid/ui/utils/shape_drawing_utils.dart';

part 'ellipse_shape_command.g.dart';

@JsonSerializable()
class EllipseShapeCommand extends ShapeCommand {
  double width;
  double height;
  @OffsetConverter()
  Offset center;
  final double angle;

  final ShapeStyle style;
  final int version;
  final String type;

  EllipseShapeCommand(
    super.paint,
    this.width,
    this.height,
    this.center,
    this.style,
    this.angle, {
    int? version,
    this.type = SerializerType.ELLIPSE_SHAPE_COMMAND,
  }) : version = version ??
            VersionStrategyManager.strategy.getEllipseShapeCommandVersion();

  Path get path {
    Path ovalPathAtOrigin = Path()
      ..addOval(Rect.fromCenter(
        center: Offset.zero,
        width: width,
        height: height,
      ));

    Path rotatedOvalPath = ovalPathAtOrigin;
    if (angle != 0.0) {
      final rotationMatrix = Matrix4.identity()..rotateZ(angle);
      rotatedOvalPath = ovalPathAtOrigin.transform(rotationMatrix.storage);
    }

    return rotatedOvalPath.shift(center);
  }

  @override
  void call(Canvas canvas) {
    ShapeDrawingUtils.drawPathWithStyle(
      canvas: canvas,
      path: path,
      basePaint: paint,
      style: style,
    );
  }

  @override
  List<Object?> get props =>
      [paint, width, height, center, style, angle];

  @override
  Map<String, dynamic> toJson() => _$EllipseShapeCommandToJson(
      this);

  factory EllipseShapeCommand.fromJson(Map<String, dynamic> json) {
    int version = json['version'] as int;
    json['angle'] = json['angle'] ?? 0.0;

    switch (version) {
      case Version.v1:
        return _$EllipseShapeCommandFromJson(json);
      case Version.v2:
      // For different versions of CircleShapeCommand the deserialization
      // has to be implemented manually.
      // Autogenerated code can only be used for one version
      default:
        return _$EllipseShapeCommandFromJson(json);
    }
  }
}
