// ignore_for_file: must_be_immutable

import 'dart:ui';

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:paintroid/core/commands/command_implementation/graphic/shape/shape_command.dart';
import 'package:paintroid/core/json_serialization/converter/offset_converter.dart';
import 'package:paintroid/core/json_serialization/converter/paint_converter.dart';
import 'package:paintroid/core/json_serialization/versioning/serializer_version.dart';
import 'package:paintroid/core/json_serialization/versioning/version_strategy.dart';

part 'ellipse_shape_command.g.dart';

@JsonSerializable()
class EllipseShapeCommand extends ShapeCommand {
  double radiusX;
  double radiusY;
  @OffsetConverter()
  Offset center;
  final double angle;
  final int version;
  final String type;

  EllipseShapeCommand(
    super.paint,
    this.radiusX,
    this.radiusY,
    this.center, {
    this.angle = 0.0,
    int? version,
    this.type = SerializerType.ELLIPSE_SHAPE_COMMAND,
  }) : version = version ??
            VersionStrategyManager.strategy.getEllipseShapeCommandVersion();

  @override
  void call(Canvas canvas) {
    canvas.save();
    canvas.translate(center.dx, center.dy);
    canvas.rotate(angle);

    final Rect ovalRect = Rect.fromCenter(
      center: Offset.zero,
      width: radiusX * 2,
      height: radiusY * 2,
    );
    canvas.drawOval(ovalRect, paint);
    canvas.restore();
  }

  @override
  List<Object?> get props =>
      [paint, radiusX, radiusY, center, angle, version, type];

  @override
  Map<String, dynamic> toJson() => _$EllipseShapeCommandToJson(this);

  factory EllipseShapeCommand.fromJson(Map<String, dynamic> json) {
    int version = json['version'] as int;

    switch (version) {
      case Version.v1:
        return _$EllipseShapeCommandFromJson(json);
      case Version.v2:
      // For different versions of SquareShapeCommand the deserialization
      // has to be implemented manually.
      // Autogenerated code can only be used for one version
      default:
        return _$EllipseShapeCommandFromJson(json);
    }
  }
}
