// ignore_for_file: must_be_immutable

import 'package:flutter/widgets.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:paintroid/core/commands/command_implementation/graphic/shape/shape_command.dart';
import 'package:paintroid/core/enums/shape_style.dart';
import 'package:paintroid/core/json_serialization/converter/offset_converter.dart';
import 'package:paintroid/core/json_serialization/converter/paint_converter.dart';
import 'package:paintroid/core/json_serialization/versioning/serializer_version.dart';
import 'package:paintroid/core/json_serialization/versioning/version_strategy.dart';
import 'package:paintroid/ui/utils/shape_drawing_utils.dart';
import 'package:paintroid/ui/utils/shape_path_generator.dart';

part 'heart_shape_command.g.dart';

@JsonSerializable()
class HeartShapeCommand extends ShapeCommand {
  final double width;
  final double height;
  final double angle;
  @OffsetConverter()
  final Offset center;

  final ShapeStyle style;
  final int version;
  final String type;

  HeartShapeCommand(
    super.paint,
    this.width,
    this.height,
    this.angle,
    this.center,
    this.style, {
    int? version,
    this.type = SerializerType.HEART_SHAPE_COMMAND,
  }) : version = version ??
            VersionStrategyManager.strategy.getHeartShapeCommandVersion();

  Path get path {
    return ShapePathUtils.generateHeartPath(
        width: width, height: height, angle: angle, center: center);
  }

  @override
  void call(Canvas canvas) {
    ShapeDrawingUtils.drawPathWithStyle(
      canvas: canvas,
      path: path,
      basePaint: paint,
      style: style,
    );
  }

  @override
  List<Object?> get props => [paint, width, height, center, style];

  @override
  Map<String, dynamic> toJson() => _$HeartShapeCommandToJson(this);

  factory HeartShapeCommand.fromJson(Map<String, dynamic> json) {
    int version = json['version'] as int;

    switch (version) {
      case Version.v1:
        return _$HeartShapeCommandFromJson(json);
      case Version.v2:
      // For different versions of CircleShapeCommand the deserialization
      // has to be implemented manually.
      // Autogenerated code can only be used for one version
      default:
        return _$HeartShapeCommandFromJson(json);
    }
  }
}
