// ignore_for_file: must_be_immutable

import 'dart:ui';

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:paintroid/core/commands/command_implementation/graphic/shape/shape_command.dart';
import 'package:paintroid/core/enums/shape_style.dart';
import 'package:paintroid/core/json_serialization/converter/offset_converter.dart';
import 'package:paintroid/core/json_serialization/converter/paint_converter.dart';
import 'package:paintroid/core/json_serialization/versioning/serializer_version.dart';
import 'package:paintroid/core/json_serialization/versioning/version_strategy.dart';
import 'package:paintroid/ui/utils/shape_drawing_utils.dart';

part 'square_shape_command.g.dart';

@JsonSerializable()
class SquareShapeCommand extends ShapeCommand {
  @OffsetConverter()
  Offset topLeft;
  @OffsetConverter()
  Offset topRight;
  @OffsetConverter()
  Offset bottomLeft;
  @OffsetConverter()
  Offset bottomRight;

  final ShapeStyle style;
  final int version;
  final String type;

  Path get path {
    final path = Path()
      ..moveTo(topLeft.dx, topLeft.dy)
      ..lineTo(topRight.dx, topRight.dy)
      ..lineTo(bottomRight.dx, bottomRight.dy)
      ..lineTo(bottomLeft.dx, bottomLeft.dy)
      ..close();
    return path;
  }

  SquareShapeCommand(
    super.paint,
    this.topLeft,
    this.topRight,
    this.bottomLeft,
    this.bottomRight,
    this.style, {
    int? version,
    this.type = SerializerType.SQUARE_SHAPE_COMMAND,
  }) : version = version ??
            VersionStrategyManager.strategy.getSquareShapeCommandVersion();

  @override
  void call(Canvas canvas) {
    ShapeDrawingUtils.drawPathWithStyle(
      canvas: canvas,
      path: path,
      basePaint: paint,
      style: style,
    );
  }

  @override
  List<Object?> get props => [
        paint,
        topLeft,
        topRight,
        bottomLeft,
        bottomRight,
        style,
      ];

  @override
  Map<String, dynamic> toJson() => _$SquareShapeCommandToJson(this);

  factory SquareShapeCommand.fromJson(Map<String, dynamic> json) {
    int version = json['version'] as int;

    switch (version) {
      case Version.v1:
        return _$SquareShapeCommandFromJson(json);
      case Version.v2:
      // For different versions of SquareShapeCommand the deserialization
      // has to be implemented manually.
      // Autogenerated code can only be used for one version
      default:
        return _$SquareShapeCommandFromJson(json);
    }
  }
}
