// ignore_for_file: must_be_immutable

import 'dart:ui';

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:paintroid/core/commands/command_implementation/graphic/shape/shape_command.dart';
import 'package:paintroid/core/enums/shape_style.dart';
import 'package:paintroid/core/json_serialization/converter/offset_converter.dart';
import 'package:paintroid/core/json_serialization/converter/paint_converter.dart';
import 'package:paintroid/core/json_serialization/versioning/serializer_version.dart';
import 'package:paintroid/core/json_serialization/versioning/version_strategy.dart';
import 'package:paintroid/ui/utils/shape_drawing_utils.dart';
import 'package:paintroid/ui/utils/shape_path_generator.dart';

part 'star_shape_command.g.dart';

@JsonSerializable()
class StarShapeCommand extends ShapeCommand {
  final int numberOfPoints;
  final double angle;
  @OffsetConverter()
  final Offset center;

  final ShapeStyle style;
  final double radiusX;
  final double radiusY;
  final int version;
  final String type;

  StarShapeCommand(
    super.paint,
    this.numberOfPoints,
    this.angle,
    this.center,
    this.style,
    this.radiusX,
    this.radiusY, {
    int? version,
    this.type = SerializerType.STAR_SHAPE_COMMAND,
  }) : version = version ??
            VersionStrategyManager.strategy.getStarShapeCommandVersion();

  Path get path {
    return ShapePathUtils.generateStarPath(
      radiusX: radiusX,
      radiusY: radiusY,
      angle: angle,
      center: center,
      numberOfPoints: numberOfPoints,
    );
  }

  @override
  void call(Canvas canvas) {
    ShapeDrawingUtils.drawPathWithStyle(
      canvas: canvas,
      path: path,
      basePaint: paint,
      style: style,
    );
  }

  @override
  List<Object?> get props =>
      [paint, numberOfPoints, center, style, radiusX, radiusY];

  @override
  Map<String, dynamic> toJson() => _$StarShapeCommandToJson(this);

  factory StarShapeCommand.fromJson(Map<String, dynamic> json) {
    int version = json['version'] as int;

    switch (version) {
      case Version.v1:
        return _$StarShapeCommandFromJson(json);
      case Version.v2:
      // For different versions of StarShapeCommand the deserialization
      // has to be implemented manually.
      // Autogenerated code can only be used for one version
      default:
        return _$StarShapeCommandFromJson(json);
    }
  }
}
