import 'dart:typed_data';
import 'dart:ui';
import 'package:collection/collection.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:paintroid/core/models/path_actions/path_action.dart';
import 'package:paintroid/core/models/path_actions/move_to_action.dart';
import 'package:paintroid/core/models/path_actions/line_to_action.dart';
import 'package:paintroid/core/models/path_actions/close_action.dart';
import 'package:paintroid/core/json_serialization/versioning/serializer_version.dart';
import 'package:paintroid/core/json_serialization/versioning/version_strategy.dart';

part 'path_model.g.dart';

@JsonSerializable(explicitToJson: true)
class PathModel {
  final int version;

  PathModel({
    int? version,
  })  : _path = Path(),
        version = version ?? VersionStrategyManager.strategy.getPathModelVersion();

  final Path _path;
  Path get nativePath => _path;
  final List<PathAction> actions = [];

  PathFillType get fillType => _path.fillType;

  set fillType(PathFillType value) => _path.fillType = value;

  void moveTo(double x, double y) {
    actions.add(MoveToAction(x, y));
    _path.moveTo(x, y);
  }

  void lineTo(double x, double y) {
    actions.add(LineToAction(x, y));
    _path.lineTo(x, y);
  }

  void close() {
    actions.add(const CloseAction());
    _path.close();
  }

  void reset() {
    actions.clear();
    _path.reset();
  }

  void relativeMoveTo(double dx, double dy) {
    _path.relativeMoveTo(dx, dy);
  }

  void relativeLineTo(double dx, double dy) {
    _path.relativeLineTo(dx, dy);
  }

  void quadraticBezierTo(double x1, double y1, double x2, double y2) {
    _path.quadraticBezierTo(x1, y1, x2, y2);
  }

  void relativeQuadraticBezierTo(double x1, double y1, double x2, double y2) {
    _path.relativeQuadraticBezierTo(x1, y1, x2, y2);
  }

  void cubicTo(
      double x1, double y1, double x2, double y2, double x3, double y3) {
    _path.cubicTo(x1, y1, x2, y2, x3, y3);
  }

  void relativeCubicTo(
      double x1, double y1, double x2, double y2, double x3, double y3) {
    _path.relativeCubicTo(x1, y1, x2, y2, x3, y3);
  }

  void conicTo(double x1, double y1, double x2, double y2, double w) {
    _path.conicTo(x1, y1, x2, y2, w);
  }

  void relativeConicTo(double x1, double y1, double x2, double y2, double w) {
    _path.relativeConicTo(x1, y1, x2, y2, w);
  }

  void arcTo(Rect rect, double startAngle, double sweepAngle, bool forceMoveTo) {
    _path.arcTo(rect, startAngle, sweepAngle, forceMoveTo);
  }

  void addRect(Rect rect) {
    _path.addRect(rect);
  }

  void addOval(Rect rect) {
    _path.addOval(rect);
  }

  void addArc(Rect rect, double startAngle, double sweepAngle) {
    _path.addArc(rect, startAngle, sweepAngle);
  }

  void addPolygon(List<Offset> points, bool close) {
    _path.addPolygon(points, close);
  }

  void addRRect(RRect rrect) {
    _path.addRRect(rrect);
  }

  void addPath(Path path, Offset offset, {Float64List? matrix4}) {
    _path.addPath(path, offset, matrix4: matrix4);
  }

  void extendWithPath(Path path, Offset offset, {Float64List? matrix4}) {
    _path.extendWithPath(path, offset, matrix4: matrix4);
  }

  bool contains(Offset point) => _path.contains(point);

  Path shift(Offset offset) => _path.shift(offset);

  Path transform(Float64List matrix4) => _path.transform(matrix4);

  Rect getBounds() => _path.getBounds();

  void arcToPoint(Offset arcEnd,
      {Radius radius = Radius.zero,
      double rotation = 0.0,
      bool largeArc = false,
      bool clockwise = true}) {
    _path.arcToPoint(arcEnd,
        radius: radius,
        rotation: rotation,
        largeArc: largeArc,
        clockwise: clockwise);
  }

  void relativeArcToPoint(Offset arcEndDelta,
      {Radius radius = Radius.zero,
      double rotation = 0.0,
      bool largeArc = false,
      bool clockwise = true}) {
    _path.relativeArcToPoint(arcEndDelta,
        radius: radius,
        rotation: rotation,
        largeArc: largeArc,
        clockwise: clockwise);
  }

  PathMetrics computeMetrics({bool forceClosed = false}) =>
      _path.computeMetrics(forceClosed: forceClosed);

  void addRSuperellipse(RSuperellipse rsuperellipse) {
    _path.addRSuperellipse(rsuperellipse);
  }

  static Path combine(PathOperation operation, Path path1, Path path2) =>
      Path.combine(operation, path1, path2);

  factory PathModel.fromJson(Map<String, dynamic> json) {
    int? version = json['version'] as int?;

    switch (version) {
      case Version.v1:
        return _fromJsonV1(json);
      case null:
        return _fromJsonV1(json);
      case Version.v2:
      // For different versions of PathModel the deserialization
      // has to be implemented manually.
      // Autogenerated code can only be used for one version
      default:
        return _fromJsonV1(json);
    }
  }

  static PathModel _fromJsonV1(Map<String, dynamic> json) {
    final model = PathModel(version: json['version'] as int?);
    final actionsJson = json['actions'] as List;
    for (var actionJson in actionsJson) {
      final action = PathAction.fromJson(actionJson as Map<String, dynamic>);
      if (action is MoveToAction) {
        model.moveTo(action.x, action.y);
      } else if (action is LineToAction) {
        model.lineTo(action.x, action.y);
      } else if (action is CloseAction) {
        model.close();
      }
    }
    return model;
  }

  Map<String, dynamic> toJson() => {
        'version': version,
        'actions': actions.map((e) => e.toJson()).toList(),
      };

  @override
  bool operator ==(Object other) {
    if (other is PathModel) {
      return const ListEquality<PathAction>().equals(actions, other.actions);
    }
    return false;
  }

  @override
  int get hashCode => const ListEquality<PathAction>().hash(actions);
}
