enum BoundingBoxCorner {
  none,
  topLeft,
  topRight,
  bottomLeft,
  bottomRight,
  topEdge,
  bottomEdge,
  leftEdge,
  rightEdge,
  topLeftRotationArc,
  topRightRotationArc,
  bottomLeftRotationArc,
  bottomRightRotationArc,
}
