// ignore_for_file: must_be_immutable

import 'dart:ui' as ui;
import 'package:flutter/foundation.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:paintroid/core/commands/command_implementation/graphic/graphic_command.dart';
import 'package:paintroid/core/json_serialization/converter/offset_converter.dart';
import 'package:paintroid/core/json_serialization/converter/paint_converter.dart';
import 'package:paintroid/core/json_serialization/converter/uint8list_base64_converter.dart';
import 'package:paintroid/core/json_serialization/versioning/serializer_version.dart';
import 'package:paintroid/core/json_serialization/versioning/version_strategy.dart';
import 'package:paintroid/core/models/loggable_mixin.dart';

part 'clipboard_command.g.dart';

@JsonSerializable()
class ClipboardCommand extends GraphicCommand with LoggableMixin {
  @Uint8ListBase64Converter()
  final Uint8List imageData;
  @OffsetConverter()
  final ui.Offset offset;
  final double scale;
  final double rotation;

  final int version;
  final String type;

  @JsonKey(includeFromJson: false, includeToJson: false)
  ui.Image? _runtimeImage;

  ClipboardCommand(
    super.paint,
    this.imageData,
    this.offset,
    this.scale,
    this.rotation, {
    int? version,
    this.type = SerializerType.CLIPBOARD_COMMAND,
  }) : version = version ??
            VersionStrategyManager.strategy.getClipboardCommandVersion();

  @override
  Future<void> prepareForRuntime() async {
    if (_runtimeImage == null && imageData.isNotEmpty) {
      try {
        final buffer = await ui.ImmutableBuffer.fromUint8List(imageData);
        final descriptor = await ui.ImageDescriptor.encoded(buffer);
        final codec = await descriptor.instantiateCodec();
        final frameInfo = await codec.getNextFrame();
        _runtimeImage = frameInfo.image;
      } catch (e, s) {
        if (kDebugMode) {
          logger.warning(
              'Error decoding image in ClipboardCommand.prepare: $e', e, s);
        }
        _runtimeImage = null;
      }
    }
  }

  @override
  void call(ui.Canvas canvas) {
    if (_runtimeImage == null) {
      if (kDebugMode) {
        logger
            .info('ClipboardCommand.call: _runtimeImage is null. Cannot draw.');
      }
      return;
    }

    canvas.save();
    canvas.translate(offset.dx, offset.dy);
    canvas.rotate(rotation);
    canvas.scale(scale);

    final imageWidth = _runtimeImage!.width.toDouble();
    final imageHeight = _runtimeImage!.height.toDouble();

    final src = ui.Rect.fromLTWH(0, 0, imageWidth, imageHeight);
    final dst = ui.Rect.fromLTWH(
      -imageWidth / 2,
      -imageHeight / 2,
      imageWidth,
      imageHeight,
    );
    final imagePaint = ui.Paint()..filterQuality = ui.FilterQuality.high;
    canvas.drawImageRect(_runtimeImage!, src, dst, imagePaint);
    canvas.restore();
  }

  @override
  List<Object?> get props => [
        paint,
        imageData,
        offset,
        scale,
        rotation,
        version,
        type,
      ];

  @override
  Map<String, dynamic> toJson() => _$ClipboardCommandToJson(this);

  factory ClipboardCommand.fromJson(Map<String, dynamic> json) {
    final int version = json['version'] as int? ?? Version.v1;
    switch (version) {
      case Version.v1:
        return _$ClipboardCommandFromJson(json);
      case Version.v2:
      // For different versions of ClipboardCommand the deserialization
      // has to be implemented manually.
      // Autogenerated code can only be used for one version
      default:
        return _$ClipboardCommandFromJson(json);
    }
  }
}
