import 'dart:ui';

import 'package:flutter/widgets.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:paintroid/core/commands/command_implementation/graphic/graphic_command.dart';
import 'package:paintroid/core/commands/path_with_action_history.dart';
import 'package:paintroid/core/json_serialization/converter/offset_converter.dart';
import 'package:paintroid/core/json_serialization/converter/path_with_action_history_converter.dart';
import 'package:paintroid/core/json_serialization/converter/paint_converter.dart';
import 'package:paintroid/core/json_serialization/versioning/serializer_version.dart';
import 'package:paintroid/core/json_serialization/versioning/version_strategy.dart';
import 'package:path_drawing/path_drawing.dart';

part 'clip_path_command.g.dart';

@JsonSerializable()
class ClipPathCommand extends GraphicCommand {
  @JsonKey(includeToJson: true, includeFromJson: true)
  final String type;
  @JsonKey(includeToJson: true, includeFromJson: true)
  final int version;

  @PathWithActionHistoryConverter()
  final PathWithActionHistory path;

  @OffsetConverter()
  final Offset? startPoint;
  @OffsetConverter()
  final Offset? endPoint;

  ClipPathCommand(
    this.path,
    super.paint, {
    this.startPoint,
    this.endPoint,
    this.type = SerializerType.CLIP_PATH_COMMAND,
    int? version,
  }) : version = version ??
            VersionStrategyManager.strategy.getClipPathCommandVersion();

  @override
  void call(Canvas canvas) {
    final dashLength = paint.strokeWidth * 4;
    final dashGap = paint.strokeWidth * 2;

    final dashedPath = dashPath(
      path.path,
      dashArray: CircularIntervalList<double>([dashLength, dashGap]),
    );
    canvas.drawPath(dashedPath, paint);

    if (startPoint != null &&
        endPoint != null &&
        (startPoint!.dx != endPoint!.dx || startPoint!.dy != endPoint!.dy)) {
      final solidPaint = Paint()
        ..color = paint.color
        ..style = PaintingStyle.stroke
        ..strokeWidth = paint.strokeWidth
        ..isAntiAlias = true;

      final solidPath = Path()
        ..moveTo(startPoint!.dx, startPoint!.dy)
        ..lineTo(endPoint!.dx, endPoint!.dy);

      canvas.drawPath(solidPath, solidPaint);
    }
  }

  @override
  List<Object?> get props => [paint, path, startPoint, endPoint, type, version];

  factory ClipPathCommand.fromJson(Map<String, dynamic> json) {
    int version = json['version'] as int;

    switch (version) {
      case Version.v1:
        return _$ClipPathCommandFromJson(json);
      case Version.v2:
      // For different versions of ClipPathCommand the deserialization
      // has to be implemented manually.
      // Autogenerated code can only be used for one version
      default:
        return _$ClipPathCommandFromJson(json);
    }
  }

  @override
  Map<String, dynamic> toJson() => _$ClipPathCommandToJson(this);
}
