// ignore_for_file: must_be_immutable

import 'dart:ui' as ui;
import 'package:flutter/painting.dart' as painting;

import 'package:flutter/foundation.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:paintroid/core/commands/command_implementation/graphic/graphic_command.dart';
import 'package:paintroid/core/json_serialization/converter/offset_converter.dart';
import 'package:paintroid/core/json_serialization/converter/paint_converter.dart';
import 'package:paintroid/core/json_serialization/converter/uint8list_base64_converter.dart';
import 'package:paintroid/core/json_serialization/versioning/serializer_version.dart';
import 'package:paintroid/core/json_serialization/versioning/version_strategy.dart';

part 'clipboard_command.g.dart';

@JsonSerializable()
class ClipboardCommand extends GraphicCommand {
  @Uint8ListBase64Converter()
  final Uint8List imageData;
  @OffsetConverter()
  final ui.Offset offset;
  final double scale;
  final double rotation;

  final int version;
  final String type;

  ui.Image? _runtimeImage;

  ClipboardCommand(
    super.paint,
    this.imageData,
    this.offset,
    this.scale,
    this.rotation, {
    int? version,
    this.type = SerializerType.CLIPBOARD_COMMAND,
  }) : version = version ??
            VersionStrategyManager.strategy.getClipboardCommandVersion();

  Future<void> prepare() async {
    _runtimeImage ??= await painting.decodeImageFromList(imageData);
  }

  @override
  void call(ui.Canvas canvas) {
    if (_runtimeImage == null) {
      if (kDebugMode) {
        print(
            'ClipboardCommand: _runtimeImage is null. Call prepare() first. Cannot draw.');
      }
      return;
    }

    canvas.save();
    canvas.translate(offset.dx, offset.dy);
    canvas.rotate(rotation);
    canvas.scale(scale);

    final imageWidth = _runtimeImage!.width.toDouble();
    final imageHeight = _runtimeImage!.height.toDouble();

    final src = ui.Rect.fromLTWH(0, 0, imageWidth, imageHeight);
    final dst = ui.Rect.fromLTWH(
      -imageWidth / 2,
      -imageHeight / 2,
      imageWidth,
      imageHeight,
    );

    canvas.drawImageRect(_runtimeImage!, src, dst, paint);
    canvas.restore();
  }

  @override
  List<Object?> get props => [
        paint,
        imageData,
        offset,
        scale,
        rotation,
        version,
        type,
      ];

  @override
  Map<String, dynamic> toJson() => _$ClipboardCommandToJson(this);

  factory ClipboardCommand.fromJson(Map<String, dynamic> json) {
    final int version = json['version'] as int? ?? Version.v1;
    switch (version) {
      case Version.v1:
        return _$ClipboardCommandFromJson(json);
      case Version.v2:
      // For different versions of ClipboardCommand the deserialization
      // has to be implemented manually.
      // Autogenerated code can only be used for one version
      default:
        return _$ClipboardCommandFromJson(json);
    }
  }
}
