import 'dart:ui';

import 'package:json_annotation/json_annotation.dart';
import 'package:paintroid/core/commands/command_implementation/graphic/graphic_command.dart';
import 'package:paintroid/core/commands/path_with_action_history.dart';
import 'package:paintroid/core/json_serialization/converter/paint_converter.dart';
import 'package:paintroid/core/json_serialization/converter/path_with_action_history_converter.dart';
import 'package:paintroid/core/json_serialization/versioning/serializer_version.dart';
import 'package:paintroid/core/json_serialization/versioning/version_strategy.dart';

part 'clip_area_command.g.dart';

@JsonSerializable()
class ClipAreaCommand extends GraphicCommand {
  @JsonKey(includeToJson: true, includeFromJson: true)
  final String type;
  @JsonKey(includeToJson: true, includeFromJson: true)
  final int version;

  @PathWithActionHistoryConverter()
  final PathWithActionHistory clipPathData;

  ClipAreaCommand(
    this.clipPathData,
    Paint paint, {
    this.type = SerializerType.CLIP_AREA_COMMAND,
    int? version,
  })  : version = version ??
            VersionStrategyManager.strategy.getClipAreaCommandVersion(),
        super(paint);

  @override
  void call(Canvas canvas) {
    final Rect canvasBounds = canvas.getLocalClipBounds();

    Path areaToClear = Path.combine(
      PathOperation.difference,
      Path()..addRect(canvasBounds),
      clipPathData.path,
    );

    canvas.drawPath(
        areaToClear,
        Paint()
          ..blendMode = BlendMode.clear
          ..style = PaintingStyle.fill);
  }

  @override
  List<Object?> get props => [paint, clipPathData, type, version];

  factory ClipAreaCommand.fromJson(Map<String, dynamic> json) {
    int version = json['version'] as int;

    switch (version) {
      case Version.v1:
        return _$ClipAreaCommandFromJson(json);
      case Version.v2:
      // For different versions of ClipAreaCommand the deserialization
      // has to be implemented manually.
      // Autogenerated code can only be used for one version
      default:
        return _$ClipAreaCommandFromJson(json);
    }
  }

  @override
  Map<String, dynamic> toJson() => _$ClipAreaCommandToJson(this);
}
