import 'dart:ui';

import 'package:json_annotation/json_annotation.dart';
import 'package:paintroid/core/commands/command_implementation/graphic/graphic_command.dart';
import 'package:paintroid/core/json_serialization/converter/color_converter.dart';
import 'package:paintroid/core/json_serialization/converter/paint_converter.dart';
import 'package:paintroid/core/json_serialization/versioning/serializer_version.dart';
import 'package:paintroid/core/json_serialization/versioning/version_strategy.dart';

part 'color_changed_command.g.dart';

@JsonSerializable()
class ColorChangedCommand extends GraphicCommand {
  final String type;
  final int version;

  @ColorConverter()
  final Color oldColor;

  @ColorConverter()
  final Color newColor;

  ColorChangedCommand({
    required this.oldColor,
    required this.newColor,
    required Paint paint,
    this.type = SerializerType.COLOR_CHANGED_COMMAND,
    int? version,
  })  : version = version ??
            VersionStrategyManager.strategy.getColorChangedCommandVersion(),
        super(paint);

  @override
  void call(Canvas canvas) {}

  @override
  List<Object?> get props => [oldColor, newColor, type, version, paint];

  @override
  Map<String, dynamic> toJson() => _$ColorChangedCommandToJson(this);

  factory ColorChangedCommand.fromJson(Map<String, dynamic> json) {
    final int version = json['version'] as int? ?? Version.v1;
    switch (version) {
      case Version.v1:
        return _$ColorChangedCommandFromJson(json);
      case Version.v2:
      // For different versions of ColorChangedCommand the deserialization
      // has to be implemented manually.
      // Autogenerated code can only be used for one version
      default:
        return _$ColorChangedCommandFromJson(json);
    }
  }
}
