import 'dart:ui';

import 'package:flutter/widgets.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:paintroid/core/commands/command_implementation/graphic/graphic_command.dart';
import 'package:paintroid/core/commands/path_with_action_history.dart';
import 'package:paintroid/core/json_serialization/converter/path_with_action_history_converter.dart';
import 'package:paintroid/core/json_serialization/converter/paint_converter.dart';
import 'package:paintroid/core/json_serialization/versioning/serializer_version.dart';
import 'package:paintroid/core/json_serialization/versioning/version_strategy.dart';
import 'package:path_drawing/path_drawing.dart';

part 'dashed_path_command.g.dart';

@JsonSerializable()
class DashedPathCommand extends GraphicCommand {
  @JsonKey(includeToJson: true, includeFromJson: true)
  final String type;
  @JsonKey(includeToJson: true, includeFromJson: true)
  final int version;

  DashedPathCommand(
    this.path,
    super.paint, {
    this.type = SerializerType.DASHED_PATH_COMMAND,
    int? version,
  }) : version = version ??
            VersionStrategyManager.strategy.getDashedPathCommandVersion();

  @PathWithActionHistoryConverter()
  final PathWithActionHistory path;

  @override
  void call(Canvas canvas) {
    final dashLength = paint.strokeWidth * 4;
    final dashGap = paint.strokeWidth * 2;

    final dashedPath = dashPath(
      path.path,
      dashArray: CircularIntervalList<double>([dashLength, dashGap]),
    );

    canvas.drawPath(dashedPath, paint);
  }

  @override
  List<Object?> get props => [paint, path, type, version];

  factory DashedPathCommand.fromJson(Map<String, dynamic> json) {
    int version = json['version'] as int;

    switch (version) {
      case Version.v1:
        return _$DashedPathCommandFromJson(json);
      case Version.v2:
      // For different versions of DashedPathCommand the deserialization
      // has to be implemented manually.
      // Autogenerated code can only be used for one version
      default:
        return _$DashedPathCommandFromJson(json);
    }
  }

  @override
  Map<String, dynamic> toJson() => _$DashedPathCommandToJson(this);
}
