// ignore_for_file: must_be_immutable

import 'dart:ui' as ui;

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:paintroid/core/commands/command_implementation/graphic/graphic_command.dart';
import 'package:paintroid/core/json_serialization/converter/paint_converter.dart';
import 'package:paintroid/core/json_serialization/converter/rect_converter.dart';
import 'package:paintroid/core/json_serialization/versioning/serializer_version.dart';
import 'package:paintroid/core/json_serialization/versioning/version_strategy.dart';

part 'delete_region_command.g.dart';

@JsonSerializable()
class DeleteRegionCommand extends GraphicCommand {
  @RectConverter()
  final ui.Rect region;

  final int version;
  final String type;

  DeleteRegionCommand(
    super.paint,
    this.region, {
    int? version,
    this.type = SerializerType.DELETE_REGION_COMMAND,
  }) : version = version ??
            VersionStrategyManager.strategy.getDeleteRegionCommandVersion();

  @override
  void call(ui.Canvas canvas) {
    final clearPaint = ui.Paint()
      ..blendMode = ui.BlendMode.clear
      ..style = ui.PaintingStyle.fill;
    canvas.drawRect(region, clearPaint);
  }

  @override
  List<Object?> get props => [
        paint,
        region,
        version,
        type,
      ];

  @override
  Map<String, dynamic> toJson() => _$DeleteRegionCommandToJson(this);

  factory DeleteRegionCommand.fromJson(Map<String, dynamic> json) {
    final int version = json['version'] as int? ?? Version.v1;
    switch (version) {
      case Version.v1:
        return _$DeleteRegionCommandFromJson(json);
      case Version.v2:
      // For different versions of DeleteRegionCommand the deserialization
      // has to be implemented manually.
      // Autogenerated code can only be used for one version
      default:
        return _$DeleteRegionCommandFromJson(json);
    }

  }
}
