// ignore_for_file: must_be_immutable

import 'package:equatable/equatable.dart';
import 'package:flutter/material.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:paintroid/core/commands/command_implementation/graphic/graphic_command.dart';
import 'package:paintroid/core/json_serialization/converter/text_style_converter.dart';
import 'package:paintroid/core/json_serialization/converter/offset_converter.dart';
import 'package:paintroid/core/json_serialization/converter/paint_converter.dart';
import 'package:paintroid/core/json_serialization/versioning/serializer_version.dart';
import 'package:paintroid/core/json_serialization/versioning/version_strategy.dart';

part 'text_command.g.dart';

@JsonSerializable()
class TextCommand extends GraphicCommand with EquatableMixin {
  @OffsetConverter()
  Offset point;
  @TextStyleConverter()
  final TextStyle style;

  final String text;
  final double rotationAngle;
  final int version;
  final String type;
  final double fontSize;
  final double scaleX;
  final double scaleY;

  TextCommand(
    this.point,
    this.text,
    this.style,
    this.fontSize,
    super.paint, {
    required this.rotationAngle,
    this.scaleX = 1.0,
    this.scaleY = 1.0,
    int? version,
    this.type = SerializerType.TEXT_COMMAND,
  }) : version =
            version ?? VersionStrategyManager.strategy.getTextCommandVersion();

  @override
  void call(Canvas canvas) {
    final textPainter = TextPainter(
      text: TextSpan(text: text, style: style.copyWith(fontSize: fontSize)),
      textDirection: TextDirection.ltr,
    );

    textPainter.layout(minWidth: 0, maxWidth: double.infinity);

    canvas.save();
    canvas.translate(point.dx, point.dy);
    canvas.rotate(rotationAngle);
    canvas.scale(scaleX, scaleY);
    final textOffset = Offset(-textPainter.width / 2, -textPainter.height / 2);
    textPainter.paint(canvas, textOffset);
    canvas.restore();
  }

  @override
  List<Object?> get props => [
        point,
        text,
        style,
        fontSize,
        rotationAngle,
        scaleX,
        scaleY,
        version,
        type,
        paint,
      ];

  @override
  bool get stringify => true;

  @override
  Map<String, dynamic> toJson() => _$TextCommandToJson(this);

  factory TextCommand.fromJson(Map<String, dynamic> json) {
    int version = json['version'] as int;
    switch (version) {
      case Version.v1:
        return _$TextCommandFromJson(json);
      case Version.v2:
      // For different versions of PathCommand the deserialization
      // has to be implemented manually.
      // Autogenerated code can only be used for one version
      default:
        return _$TextCommandFromJson(json);
    }
  }
}
