name: onboarding_screen
description: A new Flutter package project.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  smooth_page_indicator: ^1.0.0+2
  shared_preferences: ^2.0.15
  toast: ^0.3.0
  flutter_svg: ^1.1.0
  flutter_localization: ^0.1.12

  # Internal packages
  component_library:
    path: ../../component_library
  tools:
    path: ../../tools
  workspace_screen:
    path: ../workspace_screen

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^5.2.0
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^2.0.1
  floor_generator: ^1.2.0
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2
  build_runner: ^2.2.0
  freezed: ^2.4.1

flutter:
  uses-material-design: true
