arb-dir: lib/src/l10n
template-arb-file: component_library_translations_en.arb
output-localization-file: component_library_localizations.dart
output-class: ComponentLibraryLocalizations
synthetic-package: false
nullable-getter: false
