import 'dart:ui';

import 'package:command/command.dart';
import 'package:flutter/widgets.dart';
import 'package:io_library/io_library.dart';
import 'package:json_annotation/json_annotation.dart';

part 'line_command.g.dart';

@JsonSerializable()
class LineCommand extends GraphicCommand {
  final String type;
  final int version;
  bool isSourcePath = false;

  @PathWithActionHistoryConverter()
  PathWithActionHistory path;

  @OffsetConverter()
  Offset startPoint;

  @OffsetConverter()
  Offset endPoint;

  LineCommand(
    this.path,
    super.paint,
    this.startPoint,
    this.endPoint, {
    this.type = SerializerType.LINE_COMMAND,
    int? version,
  }) : version =
            version ?? VersionStrategyManager.strategy.getLineCommandVersion();

  @override
  void call(Canvas canvas) {
    canvas.drawPath(path, paint);
  }

  @override
  List<Object?> get props => [paint, path];

  void setAsSourcePath() {
    isSourcePath = true;
  }

  void updatePath(PathWithActionHistory newPath) {
    path = newPath;
  }

  @override
  Map<String, dynamic> toJson() => _$LineCommandToJson(this);

  factory LineCommand.fromJson(Map<String, dynamic> json) {
    int version = json['version'] as int;

    switch (version) {
      case Version.v1:
        return _$LineCommandFromJson(json);
      case Version.v2:
      // For different versions of DrawPathCommand the deserialization
      // has to be implemented manually.
      // Autogenerated code can only be used for one version
      default:
        return _$LineCommandFromJson(json);
    }
  }
}
