import 'dart:ui';

import 'package:command/command.dart';
import 'package:flutter/widgets.dart';
import 'package:io_library/io_library.dart';
import 'package:json_annotation/json_annotation.dart';

part 'path_command.g.dart';

@JsonSerializable()
class PathCommand extends GraphicCommand {
  final String type;
  final int version;

  @PathWithActionHistoryConverter()
  final PathWithActionHistory path;

  PathCommand(
    this.path,
    super.paint, {
    this.type = SerializerType.PATH_COMMAND,
    int? version,
  }) : version =
            version ?? VersionStrategyManager.strategy.getPathCommandVersion();

  @override
  void call(Canvas canvas) {
    canvas.drawPath(path, paint);
  }

  @override
  List<Object?> get props => [paint, path, type];

  @override
  Map<String, dynamic> toJson() => _$PathCommandToJson(this);

  factory PathCommand.fromJson(Map<String, dynamic> json) {
    int version = json['version'] as int;

    switch (version) {
      case Version.v1:
        return _$PathCommandFromJson(json);
      case Version.v2:
      // For different versions of PathCommand the deserialization
      // has to be implemented manually.
      // Autogenerated code can only be used for one version
      default:
        return _$PathCommandFromJson(json);
    }
  }
}
