name: Build, Test and Analyze

on:
  push:
  pull_request:
  workflow_dispatch:
  
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
      - uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: "3.29.2"
          channel: "stable"
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"
          architecture: x64

      - name: Setup
        run: make get

      - name: Static Analysis
        run: make lint

      - name: Unit Tests
        run: make unit

      - name: Widget Tests
        run: make widget

      - name: Integration Tests
        run: make integration

      - name: Install xmlstarlet
        run: sudo apt-get install -y xmlstarlet

      - name: Prepare App Name and Identifier
        run: |
          chmod +x ./.github/workflows/update_app_identifiers.sh
          ./.github/workflows/update_app_identifiers.sh ${{ github.event.number }}

      - name: Build release package
        run: |
          flutter build apk --release
          mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/flutter-paint-${{ github.event.number }}.apk

      - name: Zip the APK
        run: |
          cd build/app/outputs/flutter-apk
          zip flutter-paint-${{ github.event.number }}.zip flutter-paint-${{ github.event.number }}.apk

      - name: Calculate ZIP SHA256 checksum
        run: |
          sha256sum build/app/outputs/flutter-apk/flutter-paint-${{ github.event.number }}.zip > build/app/outputs/flutter-apk/checksum.txt

      - name: Upload APK ZIP
        uses: actions/upload-artifact@v4.3.3
        with:
          name: flutter-paint-apk-${{ github.event.number }}
          path: build/app/outputs/flutter-apk/flutter-paint-${{ github.event.number }}.zip

      - name: Upload Checksum
        uses: actions/upload-artifact@v4.3.3
        with:
          name: flutter-paint-checksum-${{ github.event.number }}
          path: build/app/outputs/flutter-apk/checksum.txt
